// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/scryinfo/dot/dot"
	"github.com/scryinfo/dot/dots/gindot"
	"github.com/scryinfo/dot/dots/sconfig"
)

// Injectors from wire.go:

func InitializeService() (*App, func(), error) {
	sConfig, err := sconfig.NewConfig()
	if err != nil {
		return nil, nil, err
	}
	appConfig, err := NewAppConfig(sConfig)
	if err != nil {
		return nil, nil, err
	}
	logConfig := &appConfig.Log
	logger := dot.InitLogger(logConfig)
	configRouter := &appConfig.Router
	configEngine := &appConfig.Engine
	engine, err := gindot.NewGinDot(configEngine, logger)
	if err != nil {
		return nil, nil, err
	}
	router, err := gindot.NewRouter(configRouter, engine)
	if err != nil {
		return nil, nil, err
	}
	sampleCtroller, err := NewSampleCtroller(router)
	if err != nil {
		return nil, nil, err
	}
	app := &App{
		SConfig:        sConfig,
		Logger:         logger,
		SampleCtroller: sampleCtroller,
	}
	return app, func() {
	}, nil
}
