// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/scryinfo/dot/dot"
	"github.com/scryinfo/dot/line/db/badgerdot"
	"github.com/scryinfo/dot/line/sconfig"
)

// Injectors from wire.go:

func InitializeService() (*Line, func(), error) {
	sConfig, err := sconfig.NewConfig()
	if err != nil {
		return nil, nil, err
	}
	lineConfig, err := NewLineConfig(sConfig)
	if err != nil {
		return nil, nil, err
	}
	logConfig := &lineConfig.Log
	v := dot.NewLogger(logConfig)
	badgerDbDotConfig := &lineConfig.BadgerDb
	badgerDbDot, cleanup, err := badgerdot.NewBadgerDot(badgerDbDotConfig, sConfig, v)
	if err != nil {
		return nil, nil, err
	}
	line := &Line{
		SConfig: sConfig,
		Logger:  v,
		Badger:  badgerDbDot,
	}
	return line, func() {
		cleanup()
	}, nil
}
