[log]
file_name = "log.log"
max_size = 1024000
max_backups = 3
max_age = 7
compress = false
level = "info"
add_stdout_in_debug = false
add_stdout = true
set_slog = true
[redis]
addr = "127.0.0.1:6379"
keep_max_version_count = 4
version_from_redis = false
