// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/scryinfo/dot/dot"
	"github.com/scryinfo/dot/line/db/redis_client"
	"github.com/scryinfo/dot/line/sconfig"
)

// Injectors from wire.go:

func InitializeService() (*Line, func(), error) {
	sConfig, err := sconfig.NewConfig()
	if err != nil {
		return nil, nil, err
	}
	lineConfig, err := NewLineConfig(sConfig)
	if err != nil {
		return nil, nil, err
	}
	logConfig := &lineConfig.Log
	logger := dot.NewLogger(logConfig)
	redisConfig := &lineConfig.Redis
	redisClient, cleanup, err := redis_client.NewRedisClient(redisConfig)
	if err != nil {
		return nil, nil, err
	}
	redisSample := NewRedisSample(redisClient)
	line := &Line{
		SConfig:     sConfig,
		Logger:      logger,
		RedisSample: redisSample,
	}
	return line, func() {
		cleanup()
	}, nil
}
