// Code generated by protoc-gen-go. DO NOT EDIT.
// source: config.proto

package go_out

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//--------------------------------------------------------------------
//findDot
type ReqDirs struct {
	Dirs                 []string `protobuf:"bytes,1,rep,name=dirs,proto3" json:"dirs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqDirs) Reset()         { *m = ReqDirs{} }
func (m *ReqDirs) String() string { return proto.CompactTextString(m) }
func (*ReqDirs) ProtoMessage()    {}
func (*ReqDirs) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{0}
}

func (m *ReqDirs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqDirs.Unmarshal(m, b)
}
func (m *ReqDirs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqDirs.Marshal(b, m, deterministic)
}
func (m *ReqDirs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqDirs.Merge(m, src)
}
func (m *ReqDirs) XXX_Size() int {
	return xxx_messageInfo_ReqDirs.Size(m)
}
func (m *ReqDirs) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqDirs.DiscardUnknown(m)
}

var xxx_messageInfo_ReqDirs proto.InternalMessageInfo

func (m *ReqDirs) GetDirs() []string {
	if m != nil {
		return m.Dirs
	}
	return nil
}

type ResDots struct {
	DotsInfo             string   `protobuf:"bytes,1,opt,name=dotsInfo,proto3" json:"dotsInfo,omitempty"`
	NoExistDirs          []string `protobuf:"bytes,2,rep,name=noExistDirs,proto3" json:"noExistDirs,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResDots) Reset()         { *m = ResDots{} }
func (m *ResDots) String() string { return proto.CompactTextString(m) }
func (*ResDots) ProtoMessage()    {}
func (*ResDots) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{1}
}

func (m *ResDots) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResDots.Unmarshal(m, b)
}
func (m *ResDots) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResDots.Marshal(b, m, deterministic)
}
func (m *ResDots) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResDots.Merge(m, src)
}
func (m *ResDots) XXX_Size() int {
	return xxx_messageInfo_ResDots.Size(m)
}
func (m *ResDots) XXX_DiscardUnknown() {
	xxx_messageInfo_ResDots.DiscardUnknown(m)
}

var xxx_messageInfo_ResDots proto.InternalMessageInfo

func (m *ResDots) GetDotsInfo() string {
	if m != nil {
		return m.DotsInfo
	}
	return ""
}

func (m *ResDots) GetNoExistDirs() []string {
	if m != nil {
		return m.NoExistDirs
	}
	return nil
}

func (m *ResDots) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

//---------------------------------------------------------------------
//importfile
type ReqImport struct {
	Filepath             string   `protobuf:"bytes,1,opt,name=filepath,proto3" json:"filepath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqImport) Reset()         { *m = ReqImport{} }
func (m *ReqImport) String() string { return proto.CompactTextString(m) }
func (*ReqImport) ProtoMessage()    {}
func (*ReqImport) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{2}
}

func (m *ReqImport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqImport.Unmarshal(m, b)
}
func (m *ReqImport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqImport.Marshal(b, m, deterministic)
}
func (m *ReqImport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqImport.Merge(m, src)
}
func (m *ReqImport) XXX_Size() int {
	return xxx_messageInfo_ReqImport.Size(m)
}
func (m *ReqImport) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqImport.DiscardUnknown(m)
}

var xxx_messageInfo_ReqImport proto.InternalMessageInfo

func (m *ReqImport) GetFilepath() string {
	if m != nil {
		return m.Filepath
	}
	return ""
}

type ResImport struct {
	Json                 string   `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResImport) Reset()         { *m = ResImport{} }
func (m *ResImport) String() string { return proto.CompactTextString(m) }
func (*ResImport) ProtoMessage()    {}
func (*ResImport) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{3}
}

func (m *ResImport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResImport.Unmarshal(m, b)
}
func (m *ResImport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResImport.Marshal(b, m, deterministic)
}
func (m *ResImport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResImport.Merge(m, src)
}
func (m *ResImport) XXX_Size() int {
	return xxx_messageInfo_ResImport.Size(m)
}
func (m *ResImport) XXX_DiscardUnknown() {
	xxx_messageInfo_ResImport.DiscardUnknown(m)
}

var xxx_messageInfo_ResImport proto.InternalMessageInfo

func (m *ResImport) GetJson() string {
	if m != nil {
		return m.Json
	}
	return ""
}

func (m *ResImport) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

//----------------------------------------------------------------------
//exportfile
type ReqExport struct {
	Configdata           string   `protobuf:"bytes,1,opt,name=configdata,proto3" json:"configdata,omitempty"`
	Filename             []string `protobuf:"bytes,2,rep,name=filename,proto3" json:"filename,omitempty"`
	Dotdata              string   `protobuf:"bytes,3,opt,name=dotdata,proto3" json:"dotdata,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqExport) Reset()         { *m = ReqExport{} }
func (m *ReqExport) String() string { return proto.CompactTextString(m) }
func (*ReqExport) ProtoMessage()    {}
func (*ReqExport) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{4}
}

func (m *ReqExport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqExport.Unmarshal(m, b)
}
func (m *ReqExport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqExport.Marshal(b, m, deterministic)
}
func (m *ReqExport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqExport.Merge(m, src)
}
func (m *ReqExport) XXX_Size() int {
	return xxx_messageInfo_ReqExport.Size(m)
}
func (m *ReqExport) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqExport.DiscardUnknown(m)
}

var xxx_messageInfo_ReqExport proto.InternalMessageInfo

func (m *ReqExport) GetConfigdata() string {
	if m != nil {
		return m.Configdata
	}
	return ""
}

func (m *ReqExport) GetFilename() []string {
	if m != nil {
		return m.Filename
	}
	return nil
}

func (m *ReqExport) GetDotdata() string {
	if m != nil {
		return m.Dotdata
	}
	return ""
}

type ResExport struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResExport) Reset()         { *m = ResExport{} }
func (m *ResExport) String() string { return proto.CompactTextString(m) }
func (*ResExport) ProtoMessage()    {}
func (*ResExport) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{5}
}

func (m *ResExport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResExport.Unmarshal(m, b)
}
func (m *ResExport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResExport.Marshal(b, m, deterministic)
}
func (m *ResExport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResExport.Merge(m, src)
}
func (m *ResExport) XXX_Size() int {
	return xxx_messageInfo_ResExport.Size(m)
}
func (m *ResExport) XXX_DiscardUnknown() {
	xxx_messageInfo_ResExport.DiscardUnknown(m)
}

var xxx_messageInfo_ResExport proto.InternalMessageInfo

func (m *ResExport) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*ReqDirs)(nil), "go_out.ReqDirs")
	proto.RegisterType((*ResDots)(nil), "go_out.ResDots")
	proto.RegisterType((*ReqImport)(nil), "go_out.ReqImport")
	proto.RegisterType((*ResImport)(nil), "go_out.ResImport")
	proto.RegisterType((*ReqExport)(nil), "go_out.ReqExport")
	proto.RegisterType((*ResExport)(nil), "go_out.ResExport")
}

func init() { proto.RegisterFile("config.proto", fileDescriptor_3eaf2c85e69e9ea4) }

var fileDescriptor_3eaf2c85e69e9ea4 = []byte{
	// 327 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x4d, 0x4b, 0xf3, 0x40,
	0x10, 0xc7, 0x49, 0xda, 0xa7, 0x69, 0xa6, 0xe5, 0x11, 0x17, 0x0f, 0x21, 0xa0, 0xc4, 0x5c, 0x2c,
	0x08, 0x01, 0xad, 0xfa, 0x01, 0x6a, 0x2a, 0xf4, 0x9a, 0xa3, 0x20, 0x12, 0x4d, 0x52, 0x57, 0xec,
	0x4e, 0xba, 0xbb, 0x42, 0xfd, 0x12, 0x7e, 0x66, 0xc9, 0xbe, 0xc4, 0x55, 0x14, 0xbc, 0xcd, 0xdb,
	0x6f, 0xfe, 0x33, 0xb3, 0x0b, 0xd3, 0x47, 0x64, 0x0d, 0x5d, 0x67, 0x2d, 0x47, 0x89, 0x64, 0xb4,
	0xc6, 0x7b, 0x7c, 0x95, 0xe9, 0x21, 0x04, 0x45, 0xbd, 0xcd, 0x29, 0x17, 0x84, 0xc0, 0xb0, 0xa2,
	0x5c, 0x44, 0x5e, 0x32, 0x98, 0x85, 0x85, 0xb2, 0xd3, 0xbb, 0x2e, 0x2d, 0x72, 0x94, 0x82, 0xc4,
	0x30, 0xae, 0x50, 0x8a, 0x15, 0x6b, 0x30, 0xf2, 0x12, 0x6f, 0x16, 0x16, 0xbd, 0x4f, 0x12, 0x98,
	0x30, 0x5c, 0xee, 0xa8, 0x90, 0x5d, 0xa7, 0xc8, 0x57, 0x1d, 0xdc, 0x10, 0x39, 0x80, 0x7f, 0x35,
	0xe7, 0xc8, 0xa3, 0x81, 0x42, 0xb5, 0x93, 0x9e, 0x40, 0x58, 0xd4, 0xdb, 0xd5, 0xa6, 0x45, 0x2e,
	0x3b, 0x81, 0x86, 0xbe, 0xd4, 0x6d, 0x29, 0x9f, 0xac, 0x80, 0xf5, 0xd3, 0xcb, 0xae, 0x50, 0x98,
	0x42, 0x02, 0xc3, 0x67, 0x81, 0xcc, 0x14, 0x29, 0xfb, 0xb3, 0xbf, 0xef, 0xf6, 0x2f, 0x55, 0xff,
	0xe5, 0x4e, 0x61, 0x47, 0x00, 0xfa, 0x04, 0x55, 0x29, 0x4b, 0x03, 0x3b, 0x11, 0xab, 0xcf, 0xca,
	0x4d, 0x6d, 0x36, 0xe8, 0x7d, 0x12, 0x41, 0x50, 0xa1, 0x54, 0xa0, 0x5e, 0xc0, 0xba, 0xe9, 0xb1,
	0x9a, 0xcc, 0x48, 0xf4, 0x53, 0x78, 0xce, 0x14, 0xe7, 0xef, 0x3e, 0x84, 0x39, 0xca, 0x6b, 0x25,
	0x45, 0x4e, 0x21, 0xb8, 0xa1, 0xac, 0xca, 0x51, 0x92, 0xbd, 0x4c, 0xbf, 0x42, 0x66, 0x9e, 0x20,
	0x76, 0x02, 0xfa, 0xe8, 0x57, 0xf0, 0x5f, 0x2f, 0xbd, 0x78, 0x33, 0xf8, 0xbe, 0xc3, 0xe8, 0x54,
	0xec, 0x84, 0xec, 0x89, 0xe6, 0x30, 0xb1, 0x5c, 0x27, 0xf4, 0x37, 0xe8, 0x02, 0xa6, 0x7a, 0x8f,
	0x1f, 0xa4, 0x74, 0xe2, 0x0b, 0x65, 0x76, 0x3e, 0x83, 0x50, 0x5b, 0xdf, 0x85, 0x7e, 0x45, 0x16,
	0xe3, 0x5b, 0xf3, 0xfd, 0x1e, 0x46, 0xea, 0x37, 0xce, 0x3f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x5c,
	0x2d, 0x92, 0x5b, 0x9d, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DotConfigClient is the client API for DotConfig service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DotConfigClient interface {
	FindDot(ctx context.Context, in *ReqDirs, opts ...grpc.CallOption) (*ResDots, error)
	//文件导入
	ImportByConfig(ctx context.Context, in *ReqImport, opts ...grpc.CallOption) (*ResImport, error)
	ImportByDot(ctx context.Context, in *ReqImport, opts ...grpc.CallOption) (*ResImport, error)
	//导出文件
	ExportConfig(ctx context.Context, in *ReqExport, opts ...grpc.CallOption) (*ResExport, error)
	ExportDot(ctx context.Context, in *ReqExport, opts ...grpc.CallOption) (*ResExport, error)
}

type dotConfigClient struct {
	cc *grpc.ClientConn
}

func NewDotConfigClient(cc *grpc.ClientConn) DotConfigClient {
	return &dotConfigClient{cc}
}

func (c *dotConfigClient) FindDot(ctx context.Context, in *ReqDirs, opts ...grpc.CallOption) (*ResDots, error) {
	out := new(ResDots)
	err := c.cc.Invoke(ctx, "/go_out.DotConfig/FindDot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dotConfigClient) ImportByConfig(ctx context.Context, in *ReqImport, opts ...grpc.CallOption) (*ResImport, error) {
	out := new(ResImport)
	err := c.cc.Invoke(ctx, "/go_out.DotConfig/ImportByConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dotConfigClient) ImportByDot(ctx context.Context, in *ReqImport, opts ...grpc.CallOption) (*ResImport, error) {
	out := new(ResImport)
	err := c.cc.Invoke(ctx, "/go_out.DotConfig/ImportByDot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dotConfigClient) ExportConfig(ctx context.Context, in *ReqExport, opts ...grpc.CallOption) (*ResExport, error) {
	out := new(ResExport)
	err := c.cc.Invoke(ctx, "/go_out.DotConfig/ExportConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dotConfigClient) ExportDot(ctx context.Context, in *ReqExport, opts ...grpc.CallOption) (*ResExport, error) {
	out := new(ResExport)
	err := c.cc.Invoke(ctx, "/go_out.DotConfig/ExportDot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DotConfigServer is the server API for DotConfig service.
type DotConfigServer interface {
	FindDot(context.Context, *ReqDirs) (*ResDots, error)
	//文件导入
	ImportByConfig(context.Context, *ReqImport) (*ResImport, error)
	ImportByDot(context.Context, *ReqImport) (*ResImport, error)
	//导出文件
	ExportConfig(context.Context, *ReqExport) (*ResExport, error)
	ExportDot(context.Context, *ReqExport) (*ResExport, error)
}

// UnimplementedDotConfigServer can be embedded to have forward compatible implementations.
type UnimplementedDotConfigServer struct {
}

func (*UnimplementedDotConfigServer) FindDot(ctx context.Context, req *ReqDirs) (*ResDots, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindDot not implemented")
}
func (*UnimplementedDotConfigServer) ImportByConfig(ctx context.Context, req *ReqImport) (*ResImport, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportByConfig not implemented")
}
func (*UnimplementedDotConfigServer) ImportByDot(ctx context.Context, req *ReqImport) (*ResImport, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportByDot not implemented")
}
func (*UnimplementedDotConfigServer) ExportConfig(ctx context.Context, req *ReqExport) (*ResExport, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExportConfig not implemented")
}
func (*UnimplementedDotConfigServer) ExportDot(ctx context.Context, req *ReqExport) (*ResExport, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExportDot not implemented")
}

func RegisterDotConfigServer(s *grpc.Server, srv DotConfigServer) {
	s.RegisterService(&_DotConfig_serviceDesc, srv)
}

func _DotConfig_FindDot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqDirs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DotConfigServer).FindDot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go_out.DotConfig/FindDot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DotConfigServer).FindDot(ctx, req.(*ReqDirs))
	}
	return interceptor(ctx, in, info, handler)
}

func _DotConfig_ImportByConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqImport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DotConfigServer).ImportByConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go_out.DotConfig/ImportByConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DotConfigServer).ImportByConfig(ctx, req.(*ReqImport))
	}
	return interceptor(ctx, in, info, handler)
}

func _DotConfig_ImportByDot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqImport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DotConfigServer).ImportByDot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go_out.DotConfig/ImportByDot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DotConfigServer).ImportByDot(ctx, req.(*ReqImport))
	}
	return interceptor(ctx, in, info, handler)
}

func _DotConfig_ExportConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqExport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DotConfigServer).ExportConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go_out.DotConfig/ExportConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DotConfigServer).ExportConfig(ctx, req.(*ReqExport))
	}
	return interceptor(ctx, in, info, handler)
}

func _DotConfig_ExportDot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqExport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DotConfigServer).ExportDot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go_out.DotConfig/ExportDot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DotConfigServer).ExportDot(ctx, req.(*ReqExport))
	}
	return interceptor(ctx, in, info, handler)
}

var _DotConfig_serviceDesc = grpc.ServiceDesc{
	ServiceName: "go_out.DotConfig",
	HandlerType: (*DotConfigServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindDot",
			Handler:    _DotConfig_FindDot_Handler,
		},
		{
			MethodName: "ImportByConfig",
			Handler:    _DotConfig_ImportByConfig_Handler,
		},
		{
			MethodName: "ImportByDot",
			Handler:    _DotConfig_ImportByDot_Handler,
		},
		{
			MethodName: "ExportConfig",
			Handler:    _DotConfig_ExportConfig_Handler,
		},
		{
			MethodName: "ExportDot",
			Handler:    _DotConfig_ExportDot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "config.proto",
}
