// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/scryinfo/dot/dot"
	"github.com/scryinfo/dot/dots/sconfig"
)

// Injectors from wire.go:

func InitializeService() (*App, func(), error) {
	sConfig, err := sconfig.NewConfig()
	if err != nil {
		return nil, nil, err
	}
	appConfig, err := NewAppConfig(sConfig)
	if err != nil {
		return nil, nil, err
	}
	logConfig := &appConfig.Log
	logger := dot.InitLogger(logConfig)
	app := &App{
		SConfig: sConfig,
		Logger:  logger,
	}
	return app, func() {
	}, nil
}
