// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/v1/hi.proto

package apiv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/scryinfo/dot/samples/rpc/go_out/connect/api/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// HiServiceName is the fully-qualified name of the HiService service.
	HiServiceName = "api.v1.HiService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// HiServiceHiProcedure is the fully-qualified name of the HiService's Hi RPC.
	HiServiceHiProcedure = "/api.v1.HiService/Hi"
	// HiServiceWriteProcedure is the fully-qualified name of the HiService's Write RPC.
	HiServiceWriteProcedure = "/api.v1.HiService/Write"
	// HiServiceServerStreamProcedure is the fully-qualified name of the HiService's ServerStream RPC.
	HiServiceServerStreamProcedure = "/api.v1.HiService/ServerStream"
	// HiServiceClientStreamProcedure is the fully-qualified name of the HiService's ClientStream RPC.
	HiServiceClientStreamProcedure = "/api.v1.HiService/ClientStream"
	// HiServiceBothStreamProcedure is the fully-qualified name of the HiService's BothStream RPC.
	HiServiceBothStreamProcedure = "/api.v1.HiService/BothStream"
)

// HiServiceClient is a client for the api.v1.HiService service.
type HiServiceClient interface {
	Hi(context.Context, *connect.Request[v1.HiRequest]) (*connect.Response[v1.HiResponse], error)
	Write(context.Context, *connect.Request[v1.WriteRequest]) (*connect.Response[v1.WriteResponse], error)
	ServerStream(context.Context, *connect.Request[v1.ServerStreamRequest]) (*connect.Response[v1.ServerStreamResponse], error)
	ClientStream(context.Context, *connect.Request[v1.ClientStreamRequest]) (*connect.Response[v1.ClientStreamResponse], error)
	BothStream(context.Context, *connect.Request[v1.BothStreamRequest]) (*connect.Response[v1.BothStreamResponse], error)
}

// NewHiServiceClient constructs a client for the api.v1.HiService service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewHiServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) HiServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	hiServiceMethods := v1.File_api_v1_hi_proto.Services().ByName("HiService").Methods()
	return &hiServiceClient{
		hi: connect.NewClient[v1.HiRequest, v1.HiResponse](
			httpClient,
			baseURL+HiServiceHiProcedure,
			connect.WithSchema(hiServiceMethods.ByName("Hi")),
			connect.WithClientOptions(opts...),
		),
		write: connect.NewClient[v1.WriteRequest, v1.WriteResponse](
			httpClient,
			baseURL+HiServiceWriteProcedure,
			connect.WithSchema(hiServiceMethods.ByName("Write")),
			connect.WithClientOptions(opts...),
		),
		serverStream: connect.NewClient[v1.ServerStreamRequest, v1.ServerStreamResponse](
			httpClient,
			baseURL+HiServiceServerStreamProcedure,
			connect.WithSchema(hiServiceMethods.ByName("ServerStream")),
			connect.WithClientOptions(opts...),
		),
		clientStream: connect.NewClient[v1.ClientStreamRequest, v1.ClientStreamResponse](
			httpClient,
			baseURL+HiServiceClientStreamProcedure,
			connect.WithSchema(hiServiceMethods.ByName("ClientStream")),
			connect.WithClientOptions(opts...),
		),
		bothStream: connect.NewClient[v1.BothStreamRequest, v1.BothStreamResponse](
			httpClient,
			baseURL+HiServiceBothStreamProcedure,
			connect.WithSchema(hiServiceMethods.ByName("BothStream")),
			connect.WithClientOptions(opts...),
		),
	}
}

// hiServiceClient implements HiServiceClient.
type hiServiceClient struct {
	hi           *connect.Client[v1.HiRequest, v1.HiResponse]
	write        *connect.Client[v1.WriteRequest, v1.WriteResponse]
	serverStream *connect.Client[v1.ServerStreamRequest, v1.ServerStreamResponse]
	clientStream *connect.Client[v1.ClientStreamRequest, v1.ClientStreamResponse]
	bothStream   *connect.Client[v1.BothStreamRequest, v1.BothStreamResponse]
}

// Hi calls api.v1.HiService.Hi.
func (c *hiServiceClient) Hi(ctx context.Context, req *connect.Request[v1.HiRequest]) (*connect.Response[v1.HiResponse], error) {
	return c.hi.CallUnary(ctx, req)
}

// Write calls api.v1.HiService.Write.
func (c *hiServiceClient) Write(ctx context.Context, req *connect.Request[v1.WriteRequest]) (*connect.Response[v1.WriteResponse], error) {
	return c.write.CallUnary(ctx, req)
}

// ServerStream calls api.v1.HiService.ServerStream.
func (c *hiServiceClient) ServerStream(ctx context.Context, req *connect.Request[v1.ServerStreamRequest]) (*connect.Response[v1.ServerStreamResponse], error) {
	return c.serverStream.CallUnary(ctx, req)
}

// ClientStream calls api.v1.HiService.ClientStream.
func (c *hiServiceClient) ClientStream(ctx context.Context, req *connect.Request[v1.ClientStreamRequest]) (*connect.Response[v1.ClientStreamResponse], error) {
	return c.clientStream.CallUnary(ctx, req)
}

// BothStream calls api.v1.HiService.BothStream.
func (c *hiServiceClient) BothStream(ctx context.Context, req *connect.Request[v1.BothStreamRequest]) (*connect.Response[v1.BothStreamResponse], error) {
	return c.bothStream.CallUnary(ctx, req)
}

// HiServiceHandler is an implementation of the api.v1.HiService service.
type HiServiceHandler interface {
	Hi(context.Context, *connect.Request[v1.HiRequest]) (*connect.Response[v1.HiResponse], error)
	Write(context.Context, *connect.Request[v1.WriteRequest]) (*connect.Response[v1.WriteResponse], error)
	ServerStream(context.Context, *connect.Request[v1.ServerStreamRequest]) (*connect.Response[v1.ServerStreamResponse], error)
	ClientStream(context.Context, *connect.Request[v1.ClientStreamRequest]) (*connect.Response[v1.ClientStreamResponse], error)
	BothStream(context.Context, *connect.Request[v1.BothStreamRequest]) (*connect.Response[v1.BothStreamResponse], error)
}

// NewHiServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewHiServiceHandler(svc HiServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	hiServiceMethods := v1.File_api_v1_hi_proto.Services().ByName("HiService").Methods()
	hiServiceHiHandler := connect.NewUnaryHandler(
		HiServiceHiProcedure,
		svc.Hi,
		connect.WithSchema(hiServiceMethods.ByName("Hi")),
		connect.WithHandlerOptions(opts...),
	)
	hiServiceWriteHandler := connect.NewUnaryHandler(
		HiServiceWriteProcedure,
		svc.Write,
		connect.WithSchema(hiServiceMethods.ByName("Write")),
		connect.WithHandlerOptions(opts...),
	)
	hiServiceServerStreamHandler := connect.NewUnaryHandler(
		HiServiceServerStreamProcedure,
		svc.ServerStream,
		connect.WithSchema(hiServiceMethods.ByName("ServerStream")),
		connect.WithHandlerOptions(opts...),
	)
	hiServiceClientStreamHandler := connect.NewUnaryHandler(
		HiServiceClientStreamProcedure,
		svc.ClientStream,
		connect.WithSchema(hiServiceMethods.ByName("ClientStream")),
		connect.WithHandlerOptions(opts...),
	)
	hiServiceBothStreamHandler := connect.NewUnaryHandler(
		HiServiceBothStreamProcedure,
		svc.BothStream,
		connect.WithSchema(hiServiceMethods.ByName("BothStream")),
		connect.WithHandlerOptions(opts...),
	)
	return "/api.v1.HiService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case HiServiceHiProcedure:
			hiServiceHiHandler.ServeHTTP(w, r)
		case HiServiceWriteProcedure:
			hiServiceWriteHandler.ServeHTTP(w, r)
		case HiServiceServerStreamProcedure:
			hiServiceServerStreamHandler.ServeHTTP(w, r)
		case HiServiceClientStreamProcedure:
			hiServiceClientStreamHandler.ServeHTTP(w, r)
		case HiServiceBothStreamProcedure:
			hiServiceBothStreamHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedHiServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedHiServiceHandler struct{}

func (UnimplementedHiServiceHandler) Hi(context.Context, *connect.Request[v1.HiRequest]) (*connect.Response[v1.HiResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.HiService.Hi is not implemented"))
}

func (UnimplementedHiServiceHandler) Write(context.Context, *connect.Request[v1.WriteRequest]) (*connect.Response[v1.WriteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.HiService.Write is not implemented"))
}

func (UnimplementedHiServiceHandler) ServerStream(context.Context, *connect.Request[v1.ServerStreamRequest]) (*connect.Response[v1.ServerStreamResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.HiService.ServerStream is not implemented"))
}

func (UnimplementedHiServiceHandler) ClientStream(context.Context, *connect.Request[v1.ClientStreamRequest]) (*connect.Response[v1.ClientStreamResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.HiService.ClientStream is not implemented"))
}

func (UnimplementedHiServiceHandler) BothStream(context.Context, *connect.Request[v1.BothStreamRequest]) (*connect.Response[v1.BothStreamResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.HiService.BothStream is not implemented"))
}
