// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/scryinfo/dot/dot"
	"github.com/scryinfo/dot/line/db/pebble2dot"
	"github.com/scryinfo/dot/line/oidcdot"
	"github.com/scryinfo/dot/line/oidcdot/oidc_server/oidc_storage"
	"github.com/scryinfo/dot/line/rpcdot"
	"github.com/scryinfo/dot/line/sconfig"
)

// Injectors from wire.go:

func InitializeService() (*Line, func(), error) {
	sConfig, err := sconfig.NewConfig()
	if err != nil {
		return nil, nil, err
	}
	lineConfig, err := NewLineConfig(sConfig)
	if err != nil {
		return nil, nil, err
	}
	logConfig := &lineConfig.Log
	v := dot.NewLogger(logConfig)
	authConfig := &lineConfig.AuthConfig
	connectHttpServerMux := rpcdot.NewConnectHttpServerMux()
	oidcProviderConfig := &lineConfig.OidcProvider
	oidcProvider, err := oidcdot.NewOidcProvider(oidcProviderConfig, v)
	if err != nil {
		return nil, nil, err
	}
	pebble2Config := &lineConfig.Pebble2
	pebble2, cleanup, err := pebble2dot.NewPebble2(pebble2Config, sConfig, v)
	if err != nil {
		return nil, nil, err
	}
	appSessionDaoPebble2 := oidc_storage.NewAppSessionDaoPebble2(pebble2, v)
	authService, err := oidcdot.NewAuthService(authConfig, connectHttpServerMux, oidcProvider, appSessionDaoPebble2, v)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	connectServerConfig := &lineConfig.ConnectServer
	handlerMiddle := rpcdot.NewHandlerMiddle()
	connectServer, cleanup2, err := rpcdot.NewConnetServer(connectServerConfig, sConfig, connectHttpServerMux, v, handlerMiddle)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	line := &Line{
		Logger:        v,
		AuthService:   authService,
		ConnectServer: connectServer,
	}
	return line, func() {
		cleanup2()
		cleanup()
	}, nil
}
