// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/scryinfo/dot/dot"
	"github.com/scryinfo/dot/line/oidcdot"
	"github.com/scryinfo/dot/line/rpcdot"
	"github.com/scryinfo/dot/line/sconfig"
)

// Injectors from wire.go:

func InitializeService() (*Line, func(), error) {
	sConfig, err := sconfig.NewConfig()
	if err != nil {
		return nil, nil, err
	}
	lineConfig, err := NewLineConfig(sConfig)
	if err != nil {
		return nil, nil, err
	}
	logConfig := &lineConfig.Log
	logger := dot.NewLogger(logConfig)
	connectHttpServerMux := rpcdot.NewConnectHttpServerMux()
	oidcProviderConfig := &lineConfig.OidcProvider
	oidcProvider, err := oidcdot.NewOidcProvider(oidcProviderConfig, logger)
	if err != nil {
		return nil, nil, err
	}
	authService := oidcdot.NewAuthService(connectHttpServerMux, oidcProvider, logger)
	connectServerConfig := &lineConfig.ConnectServer
	handlerMiddle := rpcdot.NewHandlerMiddle()
	connectServer, cleanup, err := rpcdot.NewConnetServer(connectServerConfig, sConfig, connectHttpServerMux, logger, handlerMiddle)
	if err != nil {
		return nil, nil, err
	}
	line := &Line{
		Logger:        logger,
		AuthService:   authService,
		ConnectServer: connectServer,
	}
	return line, func() {
		cleanup()
	}, nil
}
