// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hi.proto

package hidot

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReqData struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqData) Reset()         { *m = ReqData{} }
func (m *ReqData) String() string { return proto.CompactTextString(m) }
func (*ReqData) ProtoMessage()    {}
func (*ReqData) Descriptor() ([]byte, []int) {
	return fileDescriptor_d092a8920edeec73, []int{0}
}

func (m *ReqData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqData.Unmarshal(m, b)
}
func (m *ReqData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqData.Marshal(b, m, deterministic)
}
func (m *ReqData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqData.Merge(m, src)
}
func (m *ReqData) XXX_Size() int {
	return xxx_messageInfo_ReqData.Size(m)
}
func (m *ReqData) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqData.DiscardUnknown(m)
}

var xxx_messageInfo_ReqData proto.InternalMessageInfo

func (m *ReqData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ResData struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResData) Reset()         { *m = ResData{} }
func (m *ResData) String() string { return proto.CompactTextString(m) }
func (*ResData) ProtoMessage()    {}
func (*ResData) Descriptor() ([]byte, []int) {
	return fileDescriptor_d092a8920edeec73, []int{1}
}

func (m *ResData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResData.Unmarshal(m, b)
}
func (m *ResData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResData.Marshal(b, m, deterministic)
}
func (m *ResData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResData.Merge(m, src)
}
func (m *ResData) XXX_Size() int {
	return xxx_messageInfo_ResData.Size(m)
}
func (m *ResData) XXX_DiscardUnknown() {
	xxx_messageInfo_ResData.DiscardUnknown(m)
}

var xxx_messageInfo_ResData proto.InternalMessageInfo

func (m *ResData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*ReqData)(nil), "hidot.ReqData")
	proto.RegisterType((*ResData)(nil), "hidot.ResData")
}

func init() { proto.RegisterFile("hi.proto", fileDescriptor_d092a8920edeec73) }

var fileDescriptor_d092a8920edeec73 = []byte{
	// 156 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xc8, 0xc8, 0xd4, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcd, 0xc8, 0x4c, 0xc9, 0x2f, 0x51, 0x92, 0xe5, 0x62, 0x0f,
	0x4a, 0x2d, 0x74, 0x49, 0x2c, 0x49, 0x14, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60,
	0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x21, 0xd2, 0xc5, 0xb8, 0xa4, 0x8d, 0x74, 0xb9, 0x58,
	0x3d, 0x32, 0x5d, 0xf2, 0x4b, 0x84, 0x54, 0xb8, 0x98, 0x3c, 0x32, 0x85, 0xf8, 0xf4, 0xc0, 0x86,
	0xea, 0x41, 0x4d, 0x94, 0x42, 0xf0, 0xc1, 0x46, 0x38, 0x19, 0x45, 0x19, 0xa4, 0x67, 0x96, 0x64,
	0x94, 0x26, 0xe9, 0x25, 0xe7, 0xe7, 0xea, 0x17, 0x27, 0x17, 0x55, 0x66, 0xe6, 0xa5, 0xe5, 0xeb,
	0xa7, 0xe4, 0x97, 0xe8, 0x17, 0x27, 0xe6, 0x16, 0xe4, 0xa4, 0xea, 0xa7, 0x17, 0x15, 0x24, 0xeb,
	0xa7, 0xe7, 0xc7, 0xe7, 0x97, 0x96, 0xe8, 0x83, 0xf5, 0x26, 0xb1, 0x81, 0x9d, 0x6b, 0x0c, 0x08,
	0x00, 0x00, 0xff, 0xff, 0x34, 0xed, 0x81, 0xfe, 0xba, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HiDotClient is the client API for HiDot service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HiDotClient interface {
	Hi(ctx context.Context, in *ReqData, opts ...grpc.CallOption) (*ResData, error)
}

type hiDotClient struct {
	cc *grpc.ClientConn
}

func NewHiDotClient(cc *grpc.ClientConn) HiDotClient {
	return &hiDotClient{cc}
}

func (c *hiDotClient) Hi(ctx context.Context, in *ReqData, opts ...grpc.CallOption) (*ResData, error) {
	out := new(ResData)
	err := c.cc.Invoke(ctx, "/hidot.HiDot/Hi", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HiDotServer is the server API for HiDot service.
type HiDotServer interface {
	Hi(context.Context, *ReqData) (*ResData, error)
}

func RegisterHiDotServer(s *grpc.Server, srv HiDotServer) {
	s.RegisterService(&_HiDot_serviceDesc, srv)
}

func _HiDot_Hi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HiDotServer).Hi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hidot.HiDot/Hi",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HiDotServer).Hi(ctx, req.(*ReqData))
	}
	return interceptor(ctx, in, info, handler)
}

var _HiDot_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hidot.HiDot",
	HandlerType: (*HiDotServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hi",
			Handler:    _HiDot_Hi_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hi.proto",
}
