[log]
file_name = "log.log"
max_size = 1024000
max_backups = 3
max_age = 7
compress = false
level = "info"
add_stdout_in_debug = false
add_stdout = true
set_slog = true

[router]
relative_path = "/rpc"

[engine]
addr = ":8089"
key_file = ""
pem_file = ""
log_skip_paths = []
