
[http_client]
  disable_compression = false
  force_attempt_http2 = true
  max_conns_per_host = 10
  max_idle_conns = 10
  max_idle_conns_per_host = 10
  server_address = "http://localhost:8090"

  [http_client.tls]
    cert = ""
    key = ""
    mode = "none"
    peer_cert = ""
    root_cert = ""
    server_cert = ""

[log]
  add_stdout = true
  compress = false
  file_name = "log.log"
  level = "info"
  max_age = 7
  max_backups = 3
  max_size = 1024000
  set_slog = true
