[log]
file_name = "log.log"
max_size = 1024000
max_backups = 3
max_age = 7
compress = false
level = "info"
add_stdout = true
set_slog = true
[etcd_client]
endpoints = ["http://127.0.0.1:2379", "http://127.0.0.1:2378", "http://127.0.0.1:2377"]
# milliseconds
dial_timeout = 12000
[grpc_client_etcd]
name = "server/samples/rpc_bl"
with_default_service_config = ""
[grpc_client_etcd.tls]
mode = "none"
cert = ""
key = ""
root_cert = ""
peer_cert = ""
