[log]
file_name = "log.log"
max_size = 1024000
max_backups = 3
max_age = 7
compress = false
level = "info"
add_stdout = true
set_slog = true

[decode]
help = true
generate = ""
file = "encode.json_en"
out_file = "encode.json"
ed25519_public_key = "f3896b1ce890dc78e0e212e67f48f3aba619d8615acd80848ce8c9b3decda9ed"
x25519_private_key = "70ca0217bbbef282af0cc9706534f88d5a551d1b9cffe115ad4d2b8db7056c71"
