// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/scryinfo/dot/dot"
	"github.com/scryinfo/dot/line/sconfig"
	"github.com/scryinfo/dot/tools/ende"
)

// Injectors from wire.go:

func InitializeService() (*Line, func(), error) {
	sConfig, err := sconfig.NewConfig()
	if err != nil {
		return nil, nil, err
	}
	lineConfig, err := NewLineConfig(sConfig)
	if err != nil {
		return nil, nil, err
	}
	logConfig := &lineConfig.Log
	logger := dot.NewLogger(logConfig)
	decodeConfig := lineConfig.Decode
	decode, err := ende.NewDecode(decodeConfig)
	if err != nil {
		return nil, nil, err
	}
	line := &Line{
		SConfig: sConfig,
		Logger:  logger,
		Decode:  decode,
	}
	return line, func() {
	}, nil
}
