[etcd_server]
advertise_client_urls = ['http://127.0.0.1:2379']
advertise_peer_urls = ['http://127.0.0.1:2380']
dir = ''
initial_cluster = 'etcd1=http://127.0.0.1:2380'
initial_cluster_token = 'ClusterToken'
listen_client_urls = ['http://127.0.0.1:2379']
listen_peer_urls = ['http://127.0.0.1:2380']
log_level = 'info'
name = 'etcd1'
ready_notify_timeout = 0

[log]
add_stdout = true
compress = false
file_name = 'log.log'
level = 'info'
max_age = 7
max_backups = 3
max_size = 1024000
set_slog = true
