[log]
file_name = "log.log"
max_size = 1024000
max_backups = 3
max_age = 7
compress = false
level = "info"
add_stdout = true
set_slog = true

[etcd_server]
name = "etcd1"
listen_client_urls = ["http://127.0.0.1:2379"]
advertise_client_urls = ["http://127.0.0.1:2379"]
listen_peer_urls = ["http://127.0.0.1:2380"]
advertise_peer_urls = ["http://127.0.0.1:2380"]
initial_cluster_token = "ClusterToken"
initial_cluster = "etcd1=http://127.0.0.1:2380"
log_level = "info"
