// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/scryinfo/dot/dot"
	"github.com/scryinfo/dot/line/rpcdot"
	"github.com/scryinfo/dot/line/sconfig"
	"github.com/scryinfo/dot/samples/rpc/go_impl/connectimpl"
)

// Injectors from wire.go:

func InitializeService() (*Line, func(), error) {
	connectHttpServerMux := rpcdot.NewConnectHttpServerMux()
	sConfig, err := sconfig.NewConfig()
	if err != nil {
		return nil, nil, err
	}
	lineConfig, err := NewLineConfig(sConfig)
	if err != nil {
		return nil, nil, err
	}
	logConfig := &lineConfig.Log
	logger := dot.NewLogger(logConfig)
	hiService := connectimpl.NewHiService(connectHttpServerMux, logger)
	connectServerConfig := &lineConfig.ConnectServer
	handlerMiddle := NewHandlerMiddle()
	connectServer, cleanup, err := rpcdot.NewConnetHttpServer(connectServerConfig, connectHttpServerMux, logger, handlerMiddle)
	if err != nil {
		return nil, nil, err
	}
	line := &Line{
		HiService:         hiService,
		ConnectHttpServer: connectServer,
	}
	return line, func() {
		cleanup()
	}, nil
}
