// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/scryinfo/dot/dot"
	"github.com/scryinfo/dot/line/etcddot"
	"github.com/scryinfo/dot/line/sconfig"
)

// Injectors from wire.go:

func InitializeService() (*Line, func(), error) {
	sConfig, err := sconfig.NewConfig()
	if err != nil {
		return nil, nil, err
	}
	lineConfig, err := NewLineConfig(sConfig)
	if err != nil {
		return nil, nil, err
	}
	logConfig := &lineConfig.Log
	logger := dot.NewLogger(logConfig)
	clientConfig := &lineConfig.EtcdClient
	client, cleanup, err := etcddot.NewClient(clientConfig)
	if err != nil {
		return nil, nil, err
	}
	line := &Line{
		SConfig:    sConfig,
		Logger:     logger,
		EtcdClient: client,
	}
	return line, func() {
		cleanup()
	}, nil
}
