
[connectServer]
  addr = ":8091"
  allowCredentials = true
  allowHeaders = []
  allowMethods = ["GET", "POST", "OPTIONS"]
  allowedOrigins = []
  http1 = true
  http2 = true
  maxConcurrentStreams = 100
  optionMethods = true
  readTimeout = 0
  shutdownTimeout = 1024000
  unAuthUrls = ["*"]
  unencryptedHTTP2 = true
  writeTimeout = 0

  [connectServer.tls]
    cert = "../../config/cert/server.cert"
    key = "../../config/cert/server.key"
    mode = "secure"
    peerCert = ""
    rootCert = ""

[connectServerEtcd]
  addr = "127.0.0.1:8091"
  name = "server/samples/rpc_bl"
  ttl = 0

[etcdClient]
  dialTimeout = 12000
  endpoints = ["http://127.0.0.1:2379", "http://127.0.0.1:2378", "http://127.0.0.1:2377"]

[hiService]
  name = "etcd2"

[log]
  addStdOut = true
  compress = false
  fileName = "log.log"
  level = "info"
  maxAge = 7
  maxBackups = 3
  maxSize = 1024000
  setSlog = true
