// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/scryinfo/dot/dot"
	"github.com/scryinfo/dot/line/db/pebble2dot"
	"github.com/scryinfo/dot/line/db/pebble_service"
	"github.com/scryinfo/dot/line/rpcdot"
	"github.com/scryinfo/dot/line/sconfig"
)

// Injectors from wire.go:

func InitializeService() (*Line, func(), error) {
	sConfig, err := sconfig.NewConfig()
	if err != nil {
		return nil, nil, err
	}
	lineConfig, err := NewLineConfig(sConfig)
	if err != nil {
		return nil, nil, err
	}
	logConfig := &lineConfig.Log
	logger := dot.NewLogger(logConfig)
	pebble2Config := &lineConfig.Pebble2
	pebble2, cleanup, err := pebble2dot.NewPebble2(pebble2Config, sConfig, logger)
	if err != nil {
		return nil, nil, err
	}
	grpcServerConfig := &lineConfig.GrpcServer
	grpcServer, cleanup2, err := rpcdot.NewGrpcServer(grpcServerConfig, sConfig, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	pebbleGrpcService := pebbleservice.NewPebbleGrpcService(pebble2, grpcServer)
	line := &Line{
		SConfig:       sConfig,
		Logger:        logger,
		Pebble:        pebble2,
		PebbleService: pebbleGrpcService,
	}
	return line, func() {
		cleanup2()
		cleanup()
	}, nil
}
