[log]
file_name = "log.log"
max_size = 1024000
max_backups = 3
max_age = 7
compress = false
level = "info"
add_stdout = true
set_slog = true

[connect_server_etcd]
name = "server/samples/rpc_bl"
addr = "127.0.0.1:8090"
# seconds ttl
ttl = 10

[hi_service]
name = "etcd1"

[connect_server]
addr = ":8090"
read_timeout = 0
write_timeout = 0
max_concurrent_streams = 100
allowed_origins = []
allow_headers = []
allow_methods = ["GET", "POST", "OPTIONS"]
allow_credentials = true
un_auth_urls = ["*"]
option_methods = true
shutdown_timeout = 1024000
http1 = true
http2 = true
unencrypted_http2 = true
[connect_server.tls]
mode = "secure"
cert = "../../config/cert/server.cert"
key = "../../config/cert/server.key"
root_cert = ""
peer_cert = ""

[etcd_client]
endpoints = ["http://127.0.0.1:2379", "http://127.0.0.1:2378", "http://127.0.0.1:2377"]
# milliseconds
dial_timeout = 12000
