syntax = "proto3";
package kv.v1;

// import "google/api/annotations.proto";

// option go_package = "github.com/scryinfo/dot/samples/rpc/go_out/connect/api/v1;apiv1";
option go_package = "github.com/scryinfo/dot/line/db/pebble_service/kv_gen/connect/kv/v1;kvv1";

message KvPairSync {
  bytes key = 1;
  bytes value = 2;
  // seconds since epoch
  uint64 expire_at = 3;
  SyncMode sync = 4;
}

message KvPair {
  bytes key = 1;
  bytes value = 2;
  // seconds since epoch
  uint64 expire_at = 3;
}

enum SyncMode {
  Auto = 0;
  SYNC = 1;
  ASYNC = 2;
}

message SetRequestSync {
  bytes key = 1;
  bytes value = 2;
  uint32 ttl_seconds = 3;
  SyncMode sync = 4;
}
message SetRequest {
  bytes key = 1;
  bytes value = 2;
  uint32 ttl_seconds = 3;
}
message SetResponse {}

message GetRequest {
  bytes key = 1;
}
message GetResponse {
  bytes value = 1;
  bool found = 2;
}
message DeleteRequestSync {
  bytes key = 1;
  SyncMode sync = 2;
}
message DeleteRequest {
  bytes key = 1;
}
message DeleteResponse {}

message ScanRequest {
  bytes start = 1;
  bytes end = 2;
  int32 limit = 3;
}
message ScanResponse {
  repeated KvPair list = 1;
}
message BatchSetRequestSync {
  repeated SetRequest entries = 1;
  SyncMode sync = 2;
}
message BatchSetRequest {
  repeated SetRequest entries = 1;
}
message BatchSetResponse {}

message BatchSetKvPairRequestSync {
  repeated KvPair entries = 1;
  SyncMode sync = 2;
}
message BatchSetKvPairRequest {
  repeated KvPair entries = 1;
}
message BatchSetKvPairResponse {}


service KvService {
  rpc Set(SetRequest) returns (SetResponse);
  rpc SetKvPair(KvPair) returns (SetResponse);
  rpc Get(GetRequest) returns (GetResponse);
  rpc Delete(DeleteRequest) returns (DeleteResponse);
  rpc Scan(ScanRequest) returns (ScanResponse);
  rpc BatchSet(BatchSetRequest) returns (BatchSetResponse);
  rpc BatchSetKvPair(BatchSetKvPairRequest) returns (BatchSetKvPairResponse);

  rpc SetSync(SetRequestSync) returns (SetResponse);
  rpc SetKvPairSync(KvPairSync) returns (SetResponse);
  rpc DeleteSync(DeleteRequestSync) returns (DeleteResponse);
  rpc BatchSetSync(BatchSetRequestSync) returns (BatchSetResponse);
  rpc BatchSetKvPairSync(BatchSetKvPairRequestSync) returns (BatchSetKvPairResponse);
}

// service KvHttpService {
//   rpc Set(SetRequest) returns (SetResponse) {
//     option (google.api.http) = {
//       post: "/v1/set"
//       body: "*"
//     };
//   }
//   rpc SetKvPair(KvPair) returns (SetResponse) {
//     option (google.api.http) = {
//       post: "/v1/set_kvpair"
//       body: "*"
//     };
//   }
//   rpc Get(GetRequest) returns (GetResponse) {
//     option (google.api.http) = {get: "/v1/get/{key}"};
//   }
//   rpc Delete(DeleteRequest) returns (DeleteResponse) {
//     option (google.api.http) = {delete: "/v1/del/{key}"};
//   }
//   rpc Scan(ScanRequest) returns (ScanResponse) {
//     option (google.api.http) = {
//       post: "/v1/scan"
//       body: "*"
//     };
//   }
//   rpc BatchSet(BatchSetRequest) returns (BatchSetResponse) {
//     option (google.api.http) = {
//       post: "/v1/batchset"
//       body: "*"
//     };
//   }
//   rpc BatchSetKvPair(BatchSetKvPairRequest) returns (BatchSetKvPairResponse) {
//     option (google.api.http) = {
//       post: "/v1/batchset_kvpair"
//       body: "*"
//     };
//   }
// }
