syntax = "proto3";

package api.v1;

option go_package = "github.com/scryinfo/dot/samples/oidcs/go_out/connect/api/v1;apiv1";

import "api/v1/reqsbase.proto";

message CheckRequest {
  Reqbase reqbase = 1;
  string name = 2;
}

message CheckResponse {
  Resbase resbase = 1;
  string name = 2;
}

message LoginRequest {
  Reqbase reqbase = 1;
  string name = 2;
}

message LoginResponse {
  Resbase resbase = 1;
  string redirect_url = 2;
}

message LogoutRequest {
  Reqbase reqbase = 1;
  string data = 2;
}

message LogoutResponse {
  Resbase resbase = 1;
  string data = 2;
}

message CallbackRequest {
  Reqbase reqbase = 1;
  string data = 2;
}

message CallbackResponse {
  Resbase resbase = 1;
  string data = 2;
}

message ReshreshRequest {
  Reqbase reqbase = 1;
  string data = 2;
}

message ReshreshResponse {
  Resbase resbase = 1;
  string data = 2;
}

service AuthService {
  rpc Check(CheckRequest) returns (CheckResponse);
  rpc Login(LoginRequest) returns (LoginResponse);
  rpc Callback(CallbackRequest) returns (CallbackResponse);
  rpc Logout(LogoutRequest) returns (LogoutResponse);
  rpc Reshresh(ReshreshRequest) returns (ReshreshResponse);
}
