[log]
file_name = "log.log"
max_size = 1024000
max_backups = 3
max_age = 7
compress = false
level = "info"
add_stdout = true
set_slog = true
[grpc_client]
server_address = "localhost:8090"
[grpc_client.tls]
mode = "secure"
cert = ""
key = ""
root_cert = ""
peer_cert = "../../config/cert/server.cert"
