// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/v1/hi.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HiRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HiRequest) Reset() {
	*x = HiRequest{}
	mi := &file_api_v1_hi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HiRequest) ProtoMessage() {}

func (x *HiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_hi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HiRequest.ProtoReflect.Descriptor instead.
func (*HiRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_hi_proto_rawDescGZIP(), []int{0}
}

func (x *HiRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type HiResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HiResponse) Reset() {
	*x = HiResponse{}
	mi := &file_api_v1_hi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HiResponse) ProtoMessage() {}

func (x *HiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_hi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HiResponse.ProtoReflect.Descriptor instead.
func (*HiResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_hi_proto_rawDescGZIP(), []int{1}
}

func (x *HiResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type WriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	mi := &file_api_v1_hi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_hi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_hi_proto_rawDescGZIP(), []int{2}
}

func (x *WriteRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type WriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	mi := &file_api_v1_hi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_hi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_hi_proto_rawDescGZIP(), []int{3}
}

func (x *WriteResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type ServerStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Greeting      string                 `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerStreamRequest) Reset() {
	*x = ServerStreamRequest{}
	mi := &file_api_v1_hi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStreamRequest) ProtoMessage() {}

func (x *ServerStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_hi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStreamRequest.ProtoReflect.Descriptor instead.
func (*ServerStreamRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_hi_proto_rawDescGZIP(), []int{4}
}

func (x *ServerStreamRequest) GetGreeting() string {
	if x != nil {
		return x.Greeting
	}
	return ""
}

type ServerStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         string                 `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerStreamResponse) Reset() {
	*x = ServerStreamResponse{}
	mi := &file_api_v1_hi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStreamResponse) ProtoMessage() {}

func (x *ServerStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_hi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStreamResponse.ProtoReflect.Descriptor instead.
func (*ServerStreamResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_hi_proto_rawDescGZIP(), []int{5}
}

func (x *ServerStreamResponse) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

type ClientStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Greeting      string                 `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientStreamRequest) Reset() {
	*x = ClientStreamRequest{}
	mi := &file_api_v1_hi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientStreamRequest) ProtoMessage() {}

func (x *ClientStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_hi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientStreamRequest.ProtoReflect.Descriptor instead.
func (*ClientStreamRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_hi_proto_rawDescGZIP(), []int{6}
}

func (x *ClientStreamRequest) GetGreeting() string {
	if x != nil {
		return x.Greeting
	}
	return ""
}

type ClientStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Greeting      string                 `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientStreamResponse) Reset() {
	*x = ClientStreamResponse{}
	mi := &file_api_v1_hi_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientStreamResponse) ProtoMessage() {}

func (x *ClientStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_hi_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientStreamResponse.ProtoReflect.Descriptor instead.
func (*ClientStreamResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_hi_proto_rawDescGZIP(), []int{7}
}

func (x *ClientStreamResponse) GetGreeting() string {
	if x != nil {
		return x.Greeting
	}
	return ""
}

type BothStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Greeting      string                 `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BothStreamRequest) Reset() {
	*x = BothStreamRequest{}
	mi := &file_api_v1_hi_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BothStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BothStreamRequest) ProtoMessage() {}

func (x *BothStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_hi_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BothStreamRequest.ProtoReflect.Descriptor instead.
func (*BothStreamRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_hi_proto_rawDescGZIP(), []int{8}
}

func (x *BothStreamRequest) GetGreeting() string {
	if x != nil {
		return x.Greeting
	}
	return ""
}

type BothStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Greeting      string                 `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BothStreamResponse) Reset() {
	*x = BothStreamResponse{}
	mi := &file_api_v1_hi_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BothStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BothStreamResponse) ProtoMessage() {}

func (x *BothStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_hi_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BothStreamResponse.ProtoReflect.Descriptor instead.
func (*BothStreamResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_hi_proto_rawDescGZIP(), []int{9}
}

func (x *BothStreamResponse) GetGreeting() string {
	if x != nil {
		return x.Greeting
	}
	return ""
}

var File_api_v1_hi_proto protoreflect.FileDescriptor

const file_api_v1_hi_proto_rawDesc = "" +
	"\n" +
	"\x0fapi/v1/hi.proto\x12\x06api.v1\"\x1f\n" +
	"\tHiRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\" \n" +
	"\n" +
	"HiResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\"\n" +
	"\fWriteRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\"#\n" +
	"\rWriteResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\"1\n" +
	"\x13ServerStreamRequest\x12\x1a\n" +
	"\bgreeting\x18\x01 \x01(\tR\bgreeting\",\n" +
	"\x14ServerStreamResponse\x12\x14\n" +
	"\x05reply\x18\x01 \x01(\tR\x05reply\"1\n" +
	"\x13ClientStreamRequest\x12\x1a\n" +
	"\bgreeting\x18\x01 \x01(\tR\bgreeting\"2\n" +
	"\x14ClientStreamResponse\x12\x1a\n" +
	"\bgreeting\x18\x01 \x01(\tR\bgreeting\"/\n" +
	"\x11BothStreamRequest\x12\x1a\n" +
	"\bgreeting\x18\x01 \x01(\tR\bgreeting\"0\n" +
	"\x12BothStreamResponse\x12\x1a\n" +
	"\bgreeting\x18\x01 \x01(\tR\bgreeting2\xc9\x02\n" +
	"\tHiService\x12+\n" +
	"\x02Hi\x12\x11.api.v1.HiRequest\x1a\x12.api.v1.HiResponse\x124\n" +
	"\x05Write\x12\x14.api.v1.WriteRequest\x1a\x15.api.v1.WriteResponse\x12I\n" +
	"\fServerStream\x12\x1b.api.v1.ServerStreamRequest\x1a\x1c.api.v1.ServerStreamResponse\x12I\n" +
	"\fClientStream\x12\x1b.api.v1.ClientStreamRequest\x1a\x1c.api.v1.ClientStreamResponse\x12C\n" +
	"\n" +
	"BothStream\x12\x19.api.v1.BothStreamRequest\x1a\x1a.api.v1.BothStreamResponseB\x8f\x01\n" +
	"\n" +
	"com.api.v1B\aHiProtoP\x01Z?github.com/scryinfo/dot/samples/rpc/go_out/connect/api/v1;apiv1\xa2\x02\x03AXX\xaa\x02\x06Api.V1\xca\x02\x06Api\\V1\xe2\x02\x12Api\\V1\\GPBMetadata\xea\x02\aApi::V1b\x06proto3"

var (
	file_api_v1_hi_proto_rawDescOnce sync.Once
	file_api_v1_hi_proto_rawDescData []byte
)

func file_api_v1_hi_proto_rawDescGZIP() []byte {
	file_api_v1_hi_proto_rawDescOnce.Do(func() {
		file_api_v1_hi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_hi_proto_rawDesc), len(file_api_v1_hi_proto_rawDesc)))
	})
	return file_api_v1_hi_proto_rawDescData
}

var file_api_v1_hi_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_v1_hi_proto_goTypes = []any{
	(*HiRequest)(nil),            // 0: api.v1.HiRequest
	(*HiResponse)(nil),           // 1: api.v1.HiResponse
	(*WriteRequest)(nil),         // 2: api.v1.WriteRequest
	(*WriteResponse)(nil),        // 3: api.v1.WriteResponse
	(*ServerStreamRequest)(nil),  // 4: api.v1.ServerStreamRequest
	(*ServerStreamResponse)(nil), // 5: api.v1.ServerStreamResponse
	(*ClientStreamRequest)(nil),  // 6: api.v1.ClientStreamRequest
	(*ClientStreamResponse)(nil), // 7: api.v1.ClientStreamResponse
	(*BothStreamRequest)(nil),    // 8: api.v1.BothStreamRequest
	(*BothStreamResponse)(nil),   // 9: api.v1.BothStreamResponse
}
var file_api_v1_hi_proto_depIdxs = []int32{
	0, // 0: api.v1.HiService.Hi:input_type -> api.v1.HiRequest
	2, // 1: api.v1.HiService.Write:input_type -> api.v1.WriteRequest
	4, // 2: api.v1.HiService.ServerStream:input_type -> api.v1.ServerStreamRequest
	6, // 3: api.v1.HiService.ClientStream:input_type -> api.v1.ClientStreamRequest
	8, // 4: api.v1.HiService.BothStream:input_type -> api.v1.BothStreamRequest
	1, // 5: api.v1.HiService.Hi:output_type -> api.v1.HiResponse
	3, // 6: api.v1.HiService.Write:output_type -> api.v1.WriteResponse
	5, // 7: api.v1.HiService.ServerStream:output_type -> api.v1.ServerStreamResponse
	7, // 8: api.v1.HiService.ClientStream:output_type -> api.v1.ClientStreamResponse
	9, // 9: api.v1.HiService.BothStream:output_type -> api.v1.BothStreamResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_v1_hi_proto_init() }
func file_api_v1_hi_proto_init() {
	if File_api_v1_hi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_hi_proto_rawDesc), len(file_api_v1_hi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_hi_proto_goTypes,
		DependencyIndexes: file_api_v1_hi_proto_depIdxs,
		MessageInfos:      file_api_v1_hi_proto_msgTypes,
	}.Build()
	File_api_v1_hi_proto = out.File
	file_api_v1_hi_proto_goTypes = nil
	file_api_v1_hi_proto_depIdxs = nil
}
