
[connect_server]
  addr = ":8092"
  allow_credentials = true
  allow_headers = []
  allow_methods = ["GET", "POST", "OPTIONS"]
  allowed_origins = []
  http1 = true
  http2 = true
  max_concurrent_streams = 100
  option_methods = true
  read_timeout = 0
  shutdown_timeout = 1024000
  un_auth_urls = ["*"]
  unencrypted_http2 = true
  write_timeout = 0

  [connect_server.tls]
    cert = ""
    key = ""
    mode = "none"
    peer_cert = ""
    root_cert = ""
    server_cert = ""

[connect_server_etcd]
  addr = "127.0.0.1:8092"
  name = "server/samples/rpc_bl"
  ttl = 0

[etcd_client]
  dial_timeout = 12000
  endpoints = ["http://127.0.0.1:2379", "http://127.0.0.1:2378", "http://127.0.0.1:2377"]

[etcd_server]
  advertise_client_urls = ["http://127.0.0.1:2377"]
  advertise_peer_urls = ["http://127.0.0.1:2382"]
  initial_cluster = "etcd1=http://127.0.0.1:2380,etcd2=http://127.0.0.1:2381,etcd3=http://127.0.0.1:2382"
  initial_cluster_token = "ClusterToken"
  listen_client_urls = ["http://127.0.0.1:2377"]
  listen_peer_urls = ["http://127.0.0.1:2382"]
  log_level = "info"
  name = "etcd3"

[hi_service]
  name = "etcd3"

[log]
  add_stdout = true
  compress = false
  file_name = "log.log"
  level = "info"
  max_age = 7
  max_backups = 3
  max_size = 1024000
  set_slog = true
