syntax = "proto3";

package oidcapi.v1;

import "oidcapi/v1/reqsbase.proto";

option go_package = "github.com/scryinfo/dot/line/oidcdot/oidc_gen/oidcapi/v1;oidcapiv1";

message CheckRequest {
  Reqbase reqbase = 1;
  string name = 2;
}

message CheckResponse {
  Resbase resbase = 1;
  string name = 2;
}

message LoginRequest {
  Reqbase reqbase = 1;
  string name = 2;
}

message LoginResponse {
  Resbase resbase = 1;
  string state = 2;
  string redirect_url = 3;
}

message LogoutRequest {
  Reqbase reqbase = 1;
  string data = 2;
}

message LogoutResponse {
  Resbase resbase = 1;
  string data = 2;
}

message OidcCallbackRequest {
  Reqbase reqbase = 1;
  string code = 2;
  string state = 3;
}

message OidcCallbackResponse {
  Resbase resbase = 1;
  string access_token = 2;
  string id_token = 3;
  string user_id = 4;
  string email = 5;
}

message ReshreshRequest {
  Reqbase reqbase = 1;
  string data = 2;
}

message ReshreshResponse {
  Resbase resbase = 1;
  string data = 2;
}

message StartDeviceAuthRequest {
  Reqbase reqbase = 1;
  string data = 2;
}

message StartDeviceAuthResponse {
  Resbase resbase = 1;
  string data = 2;
}

service AuthService {
  rpc Check(CheckRequest) returns (CheckResponse);
  rpc Login(LoginRequest) returns (LoginResponse);
  rpc OidcCallback(OidcCallbackRequest) returns (OidcCallbackResponse);
  rpc Logout(LogoutRequest) returns (LogoutResponse);
  rpc Reshresh(ReshreshRequest) returns (ReshreshResponse);

  // rpc StartDeviceAuth(StartDeviceAuthRequest) returns (StartDeviceAuthResponse);
}

// service AuthDeviceService {
// }
