syntax = "proto3";

package oidcapi.v1;

import "google/protobuf/duration.proto";
import "google/protobuf/timestamp.proto";

option go_package = "github.com/scryinfo/dot/line/oidcdot/oidc_gen/oidcapi/v1;oidcapiv1";

message CodeAuthRequest {
  uint64 expire_ts = 1;
  string code = 2;
  string auth_request_id = 3;
}

message AuthRequest {
  uint64 expire_ts = 1;
  string id = 2;
  google.protobuf.Timestamp creation_date = 3;
  string application_id = 4;
  string callback_uri = 5;
  string transfer_state = 6;
  repeated string arompt = 7;
  // repeated language.Tag UiLocales = 8;
  string login_hint = 9;
  google.protobuf.Duration max_auth_age = 10;
  string user_id = 11;
  repeated string scopes = 12;
  string response_type = 13; //oidc.ResponseType
  string response_mode = 14; //oidc.ResponseMode
  string nonce = 15;
  OIDCCodeChallenge code_challenge = 16;

  bool done = 17;
  google.protobuf.Timestamp auth_time = 18;
}

message OIDCCodeChallenge {
  string challenge = 1;
  string method = 2;
}
