syntax = "proto3";

package oidcapi.v1;

import "google/protobuf/duration.proto";

option go_package = "github.com/scryinfo/dot/line/oidcdot/oidc_gen/oidcapi/v1;oidcapiv1";

enum ApplicationType {
  APPLICATION_TYPE_UNSPECIFIED = 0;
  APPLICATION_TYPE_WEB = 1; // op.ApplicationTypeWeb
  APPLICATION_TYPE_USER_AGENT = 2; // op.ApplicationTypeUserAgent
  APPLICATION_TYPE_NATIVE = 3; // op.ApplicationTypeNative
}

enum AuthMethod {
  AUTH_METHOD_UNSPECIFIED = 0;
  AUTH_METHOD_BASIC = 1; // oidc.AuthMethodBasic
  AUTH_METHOD_POST = 2; // oidc.AuthMethodPost
  AUTH_METHOD_NONE = 3; // oidc.AuthMethodNone
  AUTH_METHOD_PRIVATE_KEY_JWT = 4; // oidc.AuthMethodPrivateKeyJWT
}

enum AccessTokenType {
  ACCESS_TOKEN_TYPE_UNSPECIFIED = 0;
  ACCESS_TOKEN_TYPE_BEARER = 1; // oidc.AccessTokenTypeBearer
  ACCESS_TOKEN_TYPE_JWT = 2; // oidc.AccessTokenTypeJWT
}

enum ResponseType {
  RESPONSE_TYPE_UNSPECIFIED = 0;
  RESPONSE_TYPE_CODE = 1; // oidc.ResponseTypeCode
  RESPONSE_TYPE_ID_TOKEN = 2; // oidc.ResponseTypeIDToken
  RESPONSE_TYPE_ID_TOKEN_ONLY = 3; // oidc.ResponseTypeIDTokenOnly
}

enum ResponseMode {
  RESPONSE_MODE_UNSPECIFIED = 0;
  RESPONSE_MODE_QUERY = 1; // oidc.ResponseModeQuery
  RESPONSE_MODE_FRAGMENT = 2; // oidc.ResponseModeFragment
  RESPONSE_MODE_FORM_POST = 3; // oidc.ResponseModeFormPost
}

enum GrantType {
  GRANT_TYPE_UNSPECIFIED = 0;
  GRANT_TYPE_CODE = 1; // oidc.GrantTypeCode
  GRANT_TYPE_REFRESH_TOKEN = 2; // oidc.GrantTypeRefreshToken
  GRANT_TYPE_CLIENT_CREDENTIALS = 3; // oidc.GrantTypeClientCredentials
  GRANT_TYPE_BEARER = 4; // oidc.GrantTypeBearer
  GRANT_TYPE_TOKEN_EXCHANGE = 5; // oidc.GrantTypeTokenExchange
  GRANT_TYPE_IMPLICIT = 6; // oidc.GrantTypeImplicit
  GRANT_TYPE_DEVICE_CODE = 7; // oidc.GrantTypeDeviceCode
}

message OidcClient {
  uint64 expire_ts = 1;
  string id = 2;
  string secret_f = 3;
  string show_name_f = 4;
  repeated string redirect_uris_f = 5;
  ApplicationType application_type_f = 6;
  AuthMethod auth_method_f = 7;
  string login_url_f = 8;
  repeated ResponseType response_types_f = 9;
  repeated GrantType grant_types_f = 10;
  AccessTokenType access_token_type_f = 11;
  bool dev_mode_f = 12;
  bool id_token_userinfo_claims_assertion_f = 13;
  google.protobuf.Duration clock_skew_f = 14;
  repeated string post_logout_redirect_uri_globs_f = 15;
  repeated string redirect_uri_globs_f = 16;
}

message ClientStatus {
  uint64 expire_ts = 1;
  string id = 2; // the client id
  SignAlgorithm sign_algorithm = 3; // the client's sign algorithm
  SignAlgorithm default_algorithm = 4; // the client's default sign algorithm
}

enum SignAlgorithm {
    SIGN_ALGORITHM_UNSPECIFIED = 0;
    SIGN_ALGORITHM_EDDSA = 1;
    SIGN_ALGORITHM_HS256 = 2;
    SIGN_ALGORITHM_HS384 = 3;
    SIGN_ALGORITHM_HS512 = 4;
    SIGN_ALGORITHM_RS256 = 5;
    SIGN_ALGORITHM_RS384 = 6;
    SIGN_ALGORITHM_RS512 = 7;
    SIGN_ALGORITHM_ES256 = 8;
    SIGN_ALGORITHM_ES384 = 9;
    SIGN_ALGORITHM_ES512 = 10;
    SIGN_ALGORITHM_PS256 = 11;
    SIGN_ALGORITHM_PS384 = 12;
    SIGN_ALGORITHM_PS512 = 13;
}
