syntax = "proto3";

package oidcapi.v1;

import "google/protobuf/duration.proto";
import "oidcapi/v1/base.proto";

option go_package = "github.com/scryinfo/dot/line/oidcdot/oidc_gen/oidcapi/v1;oidcapiv1";

message OidcClient {
  uint64 expire_ts = 1;
  string id = 2;
  string secret_f = 3;
  string show_name_f = 4;
  repeated string redirect_uris_f = 5;
  ApplicationType application_type_f = 6;
  AuthMethod auth_method_f = 7;
  string login_url_f = 8;
  repeated ResponseType response_types_f = 9;
  repeated GrantType grant_types_f = 10;
  AccessTokenType access_token_type_f = 11;
  bool dev_mode_f = 12;
  bool id_token_userinfo_claims_assertion_f = 13;
  google.protobuf.Duration clock_skew_f = 14;
  repeated string post_logout_redirect_uri_globs_f = 15;
  repeated string redirect_uri_globs_f = 16;

  google.protobuf.Duration id_token_lifetime_f = 17;
}

message ClientStatus {
  uint64 expire_ts = 1;
  string id = 2; // the client id
  SignAlgorithm sign_algorithm = 3; // the client's sign algorithm
  SignAlgorithm default_algorithm = 4; // the client's default sign algorithm
}

enum SignAlgorithm {
  SIGN_ALGORITHM_UNSPECIFIED = 0;
  SIGN_ALGORITHM_EDDSA = 1;
  SIGN_ALGORITHM_HS256 = 2;
  SIGN_ALGORITHM_HS384 = 3;
  SIGN_ALGORITHM_HS512 = 4;
  SIGN_ALGORITHM_RS256 = 5;
  SIGN_ALGORITHM_RS384 = 6;
  SIGN_ALGORITHM_RS512 = 7;
  SIGN_ALGORITHM_ES256 = 8;
  SIGN_ALGORITHM_ES384 = 9;
  SIGN_ALGORITHM_ES512 = 10;
  SIGN_ALGORITHM_PS256 = 11;
  SIGN_ALGORITHM_PS384 = 12;
  SIGN_ALGORITHM_PS512 = 13;
}
