syntax = "proto3";

package oidcapi.v1;

import "google/protobuf/timestamp.proto";

option go_package = "github.com/scryinfo/dot/line/oidcdot/oidc_gen/oidcapi/v1;oidcapiv1";

message Token {
  uint64 expire_ts = 1;
  string id = 2;
  string application_id = 3;
  string subject = 4;
  string refresh_token_id = 5;
  repeated string audience = 6;
  google.protobuf.Timestamp expiration = 7;
  repeated string scopes = 8;
}

message RefreshToken {
  uint64 expire_ts = 1;
  string id = 2;
  string token = 3;
  google.protobuf.Timestamp auth_time = 4;
  repeated string amr = 5;
  repeated string audience = 6;
  string user_id = 7;
  string application_id = 8;
  google.protobuf.Timestamp expiration = 9;
  repeated string scopes = 10;
  string access_token = 11; // Token.id
}
