syntax = "proto3";

package oidcapi.v1;

option go_package = "github.com/scryinfo/dot/line/oidcdot/oidc_gen/oidcapi/v1;oidcapiv1";

message User {
  uint64 expire_ts = 1;
  string id = 2;
  string username = 3;
  string password = 4;
  string nickname = 5;
  string first_name = 6;
  string last_name = 7;
  string email = 8;
  bool email_verified = 9;
  string phone = 10;
  bool phone_verified = 11;
  string preferred_language = 12;
  bool is_admin = 13;
  UserInfoAddress address = 14;
}

message Identity {
  uint64 expire_ts = 1;
  string id = 2;
  string user_id = 3;
  string provider = 4;
  string subject = 5;
  string email = 6;
}

message UserIdentities {
  uint64 expire_ts = 1;
  string user_id = 2;
  repeated string identities = 3;
}
message UserInfoAddress {
  string formatted = 1;
  string street_address = 2;
  string locality = 3;
  string region = 4;
  string postal_code = 5;
  string country = 6;
}
