// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/scryinfo/dot/dot"
	"github.com/scryinfo/dot/line/certificate"
	"github.com/scryinfo/dot/line/db/pebble_service"
	"github.com/scryinfo/dot/line/rpcdot"
	"github.com/scryinfo/dot/line/sconfig"
)

// Injectors from wire.go:

func InitializeService() (*Line, func(), error) {
	sConfig, err := sconfig.NewConfig()
	if err != nil {
		return nil, nil, err
	}
	lineConfig, err := NewLineConfig(sConfig)
	if err != nil {
		return nil, nil, err
	}
	logConfig := &lineConfig.Log
	logger := dot.NewLogger(logConfig)
	httpClientConfig := &lineConfig.HttpClient
	baseCertificate := certificate.NewBaseCertificate(logger)
	httpClientEx, err := rpcdot.NewHttpClientEx(httpClientConfig, sConfig, baseCertificate, logger)
	if err != nil {
		return nil, nil, err
	}
	kvServiceClient := pebbleservice.NewPebbleConnectClient(httpClientEx)
	line := &Line{
		SConfig:      sConfig,
		Logger:       logger,
		PebbleClient: kvServiceClient,
	}
	return line, func() {
	}, nil
}
