// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: kv/v1/kv.proto

package kvv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KvPair struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// seconds since epoch
	ExpireAt      uint64 `protobuf:"varint,3,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KvPair) Reset() {
	*x = KvPair{}
	mi := &file_kv_v1_kv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KvPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KvPair) ProtoMessage() {}

func (x *KvPair) ProtoReflect() protoreflect.Message {
	mi := &file_kv_v1_kv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KvPair.ProtoReflect.Descriptor instead.
func (*KvPair) Descriptor() ([]byte, []int) {
	return file_kv_v1_kv_proto_rawDescGZIP(), []int{0}
}

func (x *KvPair) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *KvPair) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *KvPair) GetExpireAt() uint64 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

type SetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	TtlSeconds    uint32                 `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_kv_v1_kv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kv_v1_kv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_kv_v1_kv_proto_rawDescGZIP(), []int{1}
}

func (x *SetRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *SetRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *SetRequest) GetTtlSeconds() uint32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type SetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetResponse) Reset() {
	*x = SetResponse{}
	mi := &file_kv_v1_kv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResponse) ProtoMessage() {}

func (x *SetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kv_v1_kv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResponse.ProtoReflect.Descriptor instead.
func (*SetResponse) Descriptor() ([]byte, []int) {
	return file_kv_v1_kv_proto_rawDescGZIP(), []int{2}
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_kv_v1_kv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kv_v1_kv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_kv_v1_kv_proto_rawDescGZIP(), []int{3}
}

func (x *GetRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_kv_v1_kv_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kv_v1_kv_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_kv_v1_kv_proto_rawDescGZIP(), []int{4}
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_kv_v1_kv_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kv_v1_kv_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_kv_v1_kv_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_kv_v1_kv_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kv_v1_kv_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_kv_v1_kv_proto_rawDescGZIP(), []int{6}
}

type ScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         []byte                 `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End           []byte                 `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanRequest) Reset() {
	*x = ScanRequest{}
	mi := &file_kv_v1_kv_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRequest) ProtoMessage() {}

func (x *ScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kv_v1_kv_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRequest.ProtoReflect.Descriptor instead.
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return file_kv_v1_kv_proto_rawDescGZIP(), []int{7}
}

func (x *ScanRequest) GetStart() []byte {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *ScanRequest) GetEnd() []byte {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *ScanRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*KvPair              `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanResponse) Reset() {
	*x = ScanResponse{}
	mi := &file_kv_v1_kv_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResponse) ProtoMessage() {}

func (x *ScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kv_v1_kv_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResponse.ProtoReflect.Descriptor instead.
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return file_kv_v1_kv_proto_rawDescGZIP(), []int{8}
}

func (x *ScanResponse) GetList() []*KvPair {
	if x != nil {
		return x.List
	}
	return nil
}

type BatchSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*SetRequest          `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchSetRequest) Reset() {
	*x = BatchSetRequest{}
	mi := &file_kv_v1_kv_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchSetRequest) ProtoMessage() {}

func (x *BatchSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kv_v1_kv_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchSetRequest.ProtoReflect.Descriptor instead.
func (*BatchSetRequest) Descriptor() ([]byte, []int) {
	return file_kv_v1_kv_proto_rawDescGZIP(), []int{9}
}

func (x *BatchSetRequest) GetEntries() []*SetRequest {
	if x != nil {
		return x.Entries
	}
	return nil
}

type BatchSetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchSetResponse) Reset() {
	*x = BatchSetResponse{}
	mi := &file_kv_v1_kv_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchSetResponse) ProtoMessage() {}

func (x *BatchSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kv_v1_kv_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchSetResponse.ProtoReflect.Descriptor instead.
func (*BatchSetResponse) Descriptor() ([]byte, []int) {
	return file_kv_v1_kv_proto_rawDescGZIP(), []int{10}
}

type BatchSetKvPairRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*KvPair              `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchSetKvPairRequest) Reset() {
	*x = BatchSetKvPairRequest{}
	mi := &file_kv_v1_kv_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchSetKvPairRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchSetKvPairRequest) ProtoMessage() {}

func (x *BatchSetKvPairRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kv_v1_kv_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchSetKvPairRequest.ProtoReflect.Descriptor instead.
func (*BatchSetKvPairRequest) Descriptor() ([]byte, []int) {
	return file_kv_v1_kv_proto_rawDescGZIP(), []int{11}
}

func (x *BatchSetKvPairRequest) GetEntries() []*KvPair {
	if x != nil {
		return x.Entries
	}
	return nil
}

type BatchSetKvPairResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchSetKvPairResponse) Reset() {
	*x = BatchSetKvPairResponse{}
	mi := &file_kv_v1_kv_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchSetKvPairResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchSetKvPairResponse) ProtoMessage() {}

func (x *BatchSetKvPairResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kv_v1_kv_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchSetKvPairResponse.ProtoReflect.Descriptor instead.
func (*BatchSetKvPairResponse) Descriptor() ([]byte, []int) {
	return file_kv_v1_kv_proto_rawDescGZIP(), []int{12}
}

var File_kv_v1_kv_proto protoreflect.FileDescriptor

const file_kv_v1_kv_proto_rawDesc = "" +
	"\n" +
	"\x0ekv/v1/kv.proto\x12\x05kv.v1\"M\n" +
	"\x06KvPair\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x1b\n" +
	"\texpire_at\x18\x03 \x01(\x04R\bexpireAt\"U\n" +
	"\n" +
	"SetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\rR\n" +
	"ttlSeconds\"\r\n" +
	"\vSetResponse\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\"9\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"!\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\"\x10\n" +
	"\x0eDeleteResponse\"K\n" +
	"\vScanRequest\x12\x14\n" +
	"\x05start\x18\x01 \x01(\fR\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\fR\x03end\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"1\n" +
	"\fScanResponse\x12!\n" +
	"\x04list\x18\x01 \x03(\v2\r.kv.v1.KvPairR\x04list\">\n" +
	"\x0fBatchSetRequest\x12+\n" +
	"\aentries\x18\x01 \x03(\v2\x11.kv.v1.SetRequestR\aentries\"\x12\n" +
	"\x10BatchSetResponse\"@\n" +
	"\x15BatchSetKvPairRequest\x12'\n" +
	"\aentries\x18\x01 \x03(\v2\r.kv.v1.KvPairR\aentries\"\x18\n" +
	"\x16BatchSetKvPairResponse2\x8b\x03\n" +
	"\tKvService\x12,\n" +
	"\x03Set\x12\x11.kv.v1.SetRequest\x1a\x12.kv.v1.SetResponse\x12.\n" +
	"\tSetKvPair\x12\r.kv.v1.KvPair\x1a\x12.kv.v1.SetResponse\x12,\n" +
	"\x03Get\x12\x11.kv.v1.GetRequest\x1a\x12.kv.v1.GetResponse\x125\n" +
	"\x06Delete\x12\x14.kv.v1.DeleteRequest\x1a\x15.kv.v1.DeleteResponse\x12/\n" +
	"\x04Scan\x12\x12.kv.v1.ScanRequest\x1a\x13.kv.v1.ScanResponse\x12;\n" +
	"\bBatchSet\x12\x16.kv.v1.BatchSetRequest\x1a\x17.kv.v1.BatchSetResponse\x12M\n" +
	"\x0eBatchSetKvPair\x12\x1c.kv.v1.BatchSetKvPairRequest\x1a\x1d.kv.v1.BatchSetKvPairResponseBJZHgithub.com/scryinfo/dot/line/db/pebble_service/kv_gen/connect/kv/v1;kvv1b\x06proto3"

var (
	file_kv_v1_kv_proto_rawDescOnce sync.Once
	file_kv_v1_kv_proto_rawDescData []byte
)

func file_kv_v1_kv_proto_rawDescGZIP() []byte {
	file_kv_v1_kv_proto_rawDescOnce.Do(func() {
		file_kv_v1_kv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kv_v1_kv_proto_rawDesc), len(file_kv_v1_kv_proto_rawDesc)))
	})
	return file_kv_v1_kv_proto_rawDescData
}

var file_kv_v1_kv_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_kv_v1_kv_proto_goTypes = []any{
	(*KvPair)(nil),                 // 0: kv.v1.KvPair
	(*SetRequest)(nil),             // 1: kv.v1.SetRequest
	(*SetResponse)(nil),            // 2: kv.v1.SetResponse
	(*GetRequest)(nil),             // 3: kv.v1.GetRequest
	(*GetResponse)(nil),            // 4: kv.v1.GetResponse
	(*DeleteRequest)(nil),          // 5: kv.v1.DeleteRequest
	(*DeleteResponse)(nil),         // 6: kv.v1.DeleteResponse
	(*ScanRequest)(nil),            // 7: kv.v1.ScanRequest
	(*ScanResponse)(nil),           // 8: kv.v1.ScanResponse
	(*BatchSetRequest)(nil),        // 9: kv.v1.BatchSetRequest
	(*BatchSetResponse)(nil),       // 10: kv.v1.BatchSetResponse
	(*BatchSetKvPairRequest)(nil),  // 11: kv.v1.BatchSetKvPairRequest
	(*BatchSetKvPairResponse)(nil), // 12: kv.v1.BatchSetKvPairResponse
}
var file_kv_v1_kv_proto_depIdxs = []int32{
	0,  // 0: kv.v1.ScanResponse.list:type_name -> kv.v1.KvPair
	1,  // 1: kv.v1.BatchSetRequest.entries:type_name -> kv.v1.SetRequest
	0,  // 2: kv.v1.BatchSetKvPairRequest.entries:type_name -> kv.v1.KvPair
	1,  // 3: kv.v1.KvService.Set:input_type -> kv.v1.SetRequest
	0,  // 4: kv.v1.KvService.SetKvPair:input_type -> kv.v1.KvPair
	3,  // 5: kv.v1.KvService.Get:input_type -> kv.v1.GetRequest
	5,  // 6: kv.v1.KvService.Delete:input_type -> kv.v1.DeleteRequest
	7,  // 7: kv.v1.KvService.Scan:input_type -> kv.v1.ScanRequest
	9,  // 8: kv.v1.KvService.BatchSet:input_type -> kv.v1.BatchSetRequest
	11, // 9: kv.v1.KvService.BatchSetKvPair:input_type -> kv.v1.BatchSetKvPairRequest
	2,  // 10: kv.v1.KvService.Set:output_type -> kv.v1.SetResponse
	2,  // 11: kv.v1.KvService.SetKvPair:output_type -> kv.v1.SetResponse
	4,  // 12: kv.v1.KvService.Get:output_type -> kv.v1.GetResponse
	6,  // 13: kv.v1.KvService.Delete:output_type -> kv.v1.DeleteResponse
	8,  // 14: kv.v1.KvService.Scan:output_type -> kv.v1.ScanResponse
	10, // 15: kv.v1.KvService.BatchSet:output_type -> kv.v1.BatchSetResponse
	12, // 16: kv.v1.KvService.BatchSetKvPair:output_type -> kv.v1.BatchSetKvPairResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_kv_v1_kv_proto_init() }
func file_kv_v1_kv_proto_init() {
	if File_kv_v1_kv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kv_v1_kv_proto_rawDesc), len(file_kv_v1_kv_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kv_v1_kv_proto_goTypes,
		DependencyIndexes: file_kv_v1_kv_proto_depIdxs,
		MessageInfos:      file_kv_v1_kv_proto_msgTypes,
	}.Build()
	File_kv_v1_kv_proto = out.File
	file_kv_v1_kv_proto_goTypes = nil
	file_kv_v1_kv_proto_depIdxs = nil
}
