[log]
fileName = "log.log"
maxSize = 1024000
maxBackups = 3
maxAge = 7
compress = false
level = "info"
addStdOut = true
setSlog = true
[connectServer]
addr = ":8090"
readTimeout = 0
writeTimeout = 0
maxConcurrentStreams = 100
allowedOrigins = []
allowHeaders = []
allowMethods = ["GET", "POST", "OPTIONS"]
allowCredentials = true
unAuthUrls = ["*"]
optionMethods = true
shutdownTimeout = 1024000
http1 = false
http2 = true
unencryptedHTTP2 = false
[connectServer.tls]
mode = "secure"
cert = "../../config/cert/server.cert"
key = "../../config/cert/server.key"
rootCert = ""
peerCert = ""
[hiService]
name = "nobls_server"
