// @generated by protoc-gen-es v2.13.0 with parameter "target=ts"
// @generated from file api/v1/auth.proto (package api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/v1/auth.proto.
 */
export const file_api_v1_auth: GenFile = /*@__PURE__*/
  fileDesc("ChFhcGkvdjEvYXV0aC5wcm90bxIGYXBpLnYxIhwKDENoZWNrUmVxdWVzdBIMCgRuYW1lGAEgASgJIh0KDUNoZWNrUmVzcG9uc2USDAoEbmFtZRgBIAEoCSIcCgxMb2dpblJlcXVlc3QSDAoEbmFtZRgBIAEoCSIdCg1Mb2dpblJlc3BvbnNlEgwKBG5hbWUYASABKAkiHQoNTG9nb3V0UmVxdWVzdBIMCgRkYXRhGAEgASgJIh4KDkxvZ291dFJlc3BvbnNlEgwKBGRhdGEYASABKAkiHwoPQ2FsbGJhY2tSZXF1ZXN0EgwKBGRhdGEYASABKAkiIAoQQ2FsbGJhY2tSZXNwb25zZRIMCgRkYXRhGAEgASgJIh8KD1Jlc2hyZXNoUmVxdWVzdBIMCgRkYXRhGAEgASgJIiAKEFJlc2hyZXNoUmVzcG9uc2USDAoEZGF0YRgBIAEoCTKwAgoLQXV0aFNlcnZpY2USNAoFQ2hlY2sSFC5hcGkudjEuQ2hlY2tSZXF1ZXN0GhUuYXBpLnYxLkNoZWNrUmVzcG9uc2USNAoFTG9naW4SFC5hcGkudjEuTG9naW5SZXF1ZXN0GhUuYXBpLnYxLkxvZ2luUmVzcG9uc2USPQoIQ2FsbGJhY2sSFy5hcGkudjEuQ2FsbGJhY2tSZXF1ZXN0GhguYXBpLnYxLkNhbGxiYWNrUmVzcG9uc2USNwoGTG9nb3V0EhUuYXBpLnYxLkxvZ291dFJlcXVlc3QaFi5hcGkudjEuTG9nb3V0UmVzcG9uc2USPQoIUmVzaHJlc2gSFy5hcGkudjEuUmVzaHJlc2hSZXF1ZXN0GhguYXBpLnYxLlJlc2hyZXNoUmVzcG9uc2VCkwEKCmNvbS5hcGkudjFCCUF1dGhQcm90b1ABWkFnaXRodWIuY29tL3NjcnlpbmZvL2RvdC9zYW1wbGVzL29pZGNzL2dvX291dC9jb25uZWN0L2FwaS92MTthcGl2MaICA0FYWKoCBkFwaS5WMcoCBkFwaVxWMeICEkFwaVxWMVxHUEJNZXRhZGF0YeoCB0FwaTo6VjFiBnByb3RvMw");

/**
 * @generated from message api.v1.CheckRequest
 */
export type CheckRequest = Message<"api.v1.CheckRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message api.v1.CheckRequest.
 * Use `create(CheckRequestSchema)` to create a new message.
 */
export const CheckRequestSchema: GenMessage<CheckRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_auth, 0);

/**
 * @generated from message api.v1.CheckResponse
 */
export type CheckResponse = Message<"api.v1.CheckResponse"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message api.v1.CheckResponse.
 * Use `create(CheckResponseSchema)` to create a new message.
 */
export const CheckResponseSchema: GenMessage<CheckResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_auth, 1);

/**
 * @generated from message api.v1.LoginRequest
 */
export type LoginRequest = Message<"api.v1.LoginRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message api.v1.LoginRequest.
 * Use `create(LoginRequestSchema)` to create a new message.
 */
export const LoginRequestSchema: GenMessage<LoginRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_auth, 2);

/**
 * @generated from message api.v1.LoginResponse
 */
export type LoginResponse = Message<"api.v1.LoginResponse"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message api.v1.LoginResponse.
 * Use `create(LoginResponseSchema)` to create a new message.
 */
export const LoginResponseSchema: GenMessage<LoginResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_auth, 3);

/**
 * @generated from message api.v1.LogoutRequest
 */
export type LogoutRequest = Message<"api.v1.LogoutRequest"> & {
  /**
   * @generated from field: string data = 1;
   */
  data: string;
};

/**
 * Describes the message api.v1.LogoutRequest.
 * Use `create(LogoutRequestSchema)` to create a new message.
 */
export const LogoutRequestSchema: GenMessage<LogoutRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_auth, 4);

/**
 * @generated from message api.v1.LogoutResponse
 */
export type LogoutResponse = Message<"api.v1.LogoutResponse"> & {
  /**
   * @generated from field: string data = 1;
   */
  data: string;
};

/**
 * Describes the message api.v1.LogoutResponse.
 * Use `create(LogoutResponseSchema)` to create a new message.
 */
export const LogoutResponseSchema: GenMessage<LogoutResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_auth, 5);

/**
 * @generated from message api.v1.CallbackRequest
 */
export type CallbackRequest = Message<"api.v1.CallbackRequest"> & {
  /**
   * @generated from field: string data = 1;
   */
  data: string;
};

/**
 * Describes the message api.v1.CallbackRequest.
 * Use `create(CallbackRequestSchema)` to create a new message.
 */
export const CallbackRequestSchema: GenMessage<CallbackRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_auth, 6);

/**
 * @generated from message api.v1.CallbackResponse
 */
export type CallbackResponse = Message<"api.v1.CallbackResponse"> & {
  /**
   * @generated from field: string data = 1;
   */
  data: string;
};

/**
 * Describes the message api.v1.CallbackResponse.
 * Use `create(CallbackResponseSchema)` to create a new message.
 */
export const CallbackResponseSchema: GenMessage<CallbackResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_auth, 7);

/**
 * @generated from message api.v1.ReshreshRequest
 */
export type ReshreshRequest = Message<"api.v1.ReshreshRequest"> & {
  /**
   * @generated from field: string data = 1;
   */
  data: string;
};

/**
 * Describes the message api.v1.ReshreshRequest.
 * Use `create(ReshreshRequestSchema)` to create a new message.
 */
export const ReshreshRequestSchema: GenMessage<ReshreshRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_auth, 8);

/**
 * @generated from message api.v1.ReshreshResponse
 */
export type ReshreshResponse = Message<"api.v1.ReshreshResponse"> & {
  /**
   * @generated from field: string data = 1;
   */
  data: string;
};

/**
 * Describes the message api.v1.ReshreshResponse.
 * Use `create(ReshreshResponseSchema)` to create a new message.
 */
export const ReshreshResponseSchema: GenMessage<ReshreshResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_auth, 9);

/**
 * @generated from service api.v1.AuthService
 */
export const AuthService: GenService<{
  /**
   * @generated from rpc api.v1.AuthService.Check
   */
  check: {
    methodKind: "unary";
    input: typeof CheckRequestSchema;
    output: typeof CheckResponseSchema;
  },
  /**
   * @generated from rpc api.v1.AuthService.Login
   */
  login: {
    methodKind: "unary";
    input: typeof LoginRequestSchema;
    output: typeof LoginResponseSchema;
  },
  /**
   * @generated from rpc api.v1.AuthService.Callback
   */
  callback: {
    methodKind: "unary";
    input: typeof CallbackRequestSchema;
    output: typeof CallbackResponseSchema;
  },
  /**
   * @generated from rpc api.v1.AuthService.Logout
   */
  logout: {
    methodKind: "unary";
    input: typeof LogoutRequestSchema;
    output: typeof LogoutResponseSchema;
  },
  /**
   * @generated from rpc api.v1.AuthService.Reshresh
   */
  reshresh: {
    methodKind: "unary";
    input: typeof ReshreshRequestSchema;
    output: typeof ReshreshResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_v1_auth, 0);

