
[[etcdServers]]
  advertiseClientUrls = ["http://127.0.0.1:2379"]
  advertisePeerUrls = ["http://127.0.0.1:2380"]
  dir = "default.etcd1"
  initialCluster = "etcd1=http://127.0.0.1:2380,etcd2=http://127.0.0.1:2381,etcd3=http://127.0.0.1:2382"
  initialClusterToken = "ClusterToken"
  listenClientUrls = ["http://127.0.0.1:2379"]
  listenPeerUrls = ["http://127.0.0.1:2380"]
  logLevel = "info"
  name = "etcd1"

[[etcdServers]]
  advertiseClientUrls = ["http://127.0.0.1:2378"]
  advertisePeerUrls = ["http://127.0.0.1:2381"]
  dir = "default.etcd2"
  initialCluster = "etcd1=http://127.0.0.1:2380,etcd2=http://127.0.0.1:2381,etcd3=http://127.0.0.1:2382"
  initialClusterToken = "ClusterToken"
  listenClientUrls = ["http://127.0.0.1:2378"]
  listenPeerUrls = ["http://127.0.0.1:2381"]
  logLevel = "info"
  name = "etcd2"

[[etcdServers]]
  advertiseClientUrls = ["http://127.0.0.1:2377"]
  advertisePeerUrls = ["http://127.0.0.1:2382"]
  dir = "default.etcd3"
  initialCluster = "etcd1=http://127.0.0.1:2380,etcd2=http://127.0.0.1:2381,etcd3=http://127.0.0.1:2382"
  initialClusterToken = "ClusterToken"
  listenClientUrls = ["http://127.0.0.1:2377"]
  listenPeerUrls = ["http://127.0.0.1:2382"]
  logLevel = "info"
  name = "etcd3"

[log]
  addStdOut = true
  compress = false
  fileName = "log.log"
  level = "info"
  maxAge = 7
  maxBackups = 3
  maxSize = 1024000
  setSlog = true
