[log]
fileName = "log.log"
maxSize = 1024000
maxBackups = 3
maxAge = 7
compress = false
level = "info"
addStdOut = true
setSlog = true
[[etcdServers]]
name = "etcd1"
dir = "default.etcd1"
listenClientUrls = ["http://127.0.0.1:2379"]
advertiseClientUrls = ["http://127.0.0.1:2379"]
listenPeerUrls = ["http://127.0.0.1:2380"]
advertisePeerUrls = ["http://127.0.0.1:2380"]
initialClusterToken = "ClusterToken"
initialCluster = "etcd1=http://127.0.0.1:2380,etcd2=http://127.0.0.1:2381,etcd3=http://127.0.0.1:2382"
logLevel = "info"

[[etcdServers]]
name = "etcd2"
dir = "default.etcd2"
listenClientUrls = ["http://127.0.0.1:2378"]
advertiseClientUrls = ["http://127.0.0.1:2378"]
listenPeerUrls = ["http://127.0.0.1:2381"]
advertisePeerUrls = ["http://127.0.0.1:2381"]
initialClusterToken = "ClusterToken"
initialCluster = "etcd1=http://127.0.0.1:2380,etcd2=http://127.0.0.1:2381,etcd3=http://127.0.0.1:2382"
logLevel = "info"

[[etcdServers]]
name = "etcd3"
dir = "default.etcd3"
listenClientUrls = ["http://127.0.0.1:2377"]
advertiseClientUrls = ["http://127.0.0.1:2377"]
listenPeerUrls = ["http://127.0.0.1:2382"]
advertisePeerUrls = ["http://127.0.0.1:2382"]
initialClusterToken = "ClusterToken"
initialCluster = "etcd1=http://127.0.0.1:2380,etcd2=http://127.0.0.1:2381,etcd3=http://127.0.0.1:2382"
logLevel = "info"
