// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file api/v1/hi.proto (package api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from '@bufbuild/protobuf/codegenv2'
import { fileDesc, messageDesc, serviceDesc } from '@bufbuild/protobuf/codegenv2'
import type { Message } from '@bufbuild/protobuf'

/**
 * Describes the file api/v1/hi.proto.
 */
export const file_api_v1_hi: GenFile /*@__PURE__*/ = fileDesc(
  'Cg9hcGkvdjEvaGkucHJvdG8SBmFwaS52MSIZCglIaVJlcXVlc3QSDAoEbmFtZRgBIAEoCSIaCgpIaVJlc3BvbnNlEgwKBG5hbWUYASABKAkiHAoMV3JpdGVSZXF1ZXN0EgwKBGRhdGEYASABKAkiHQoNV3JpdGVSZXNwb25zZRIMCgRkYXRhGAEgASgJIicKE1NlcnZlclN0cmVhbVJlcXVlc3QSEAoIZ3JlZXRpbmcYASABKAkiJQoUU2VydmVyU3RyZWFtUmVzcG9uc2USDQoFcmVwbHkYASABKAkiJwoTQ2xpZW50U3RyZWFtUmVxdWVzdBIQCghncmVldGluZxgBIAEoCSIoChRDbGllbnRTdHJlYW1SZXNwb25zZRIQCghncmVldGluZxgBIAEoCSIlChFCb3RoU3RyZWFtUmVxdWVzdBIQCghncmVldGluZxgBIAEoCSImChJCb3RoU3RyZWFtUmVzcG9uc2USEAoIZ3JlZXRpbmcYASABKAky0QIKCUhpU2VydmljZRIrCgJIaRIRLmFwaS52MS5IaVJlcXVlc3QaEi5hcGkudjEuSGlSZXNwb25zZRI0CgVXcml0ZRIULmFwaS52MS5Xcml0ZVJlcXVlc3QaFS5hcGkudjEuV3JpdGVSZXNwb25zZRJLCgxTZXJ2ZXJTdHJlYW0SGy5hcGkudjEuU2VydmVyU3RyZWFtUmVxdWVzdBocLmFwaS52MS5TZXJ2ZXJTdHJlYW1SZXNwb25zZTABEksKDENsaWVudFN0cmVhbRIbLmFwaS52MS5DbGllbnRTdHJlYW1SZXF1ZXN0GhwuYXBpLnYxLkNsaWVudFN0cmVhbVJlc3BvbnNlKAESRwoKQm90aFN0cmVhbRIZLmFwaS52MS5Cb3RoU3RyZWFtUmVxdWVzdBoaLmFwaS52MS5Cb3RoU3RyZWFtUmVzcG9uc2UoATABQo8BCgpjb20uYXBpLnYxQgdIaVByb3RvUAFaP2dpdGh1Yi5jb20vc2NyeWluZm8vZG90L3NhbXBsZXMvcnBjL2dvX291dC9jb25uZWN0L2FwaS92MTthcGl2MaICA0FYWKoCBkFwaS5WMcoCBkFwaVxWMeICEkFwaVxWMVxHUEJNZXRhZGF0YeoCB0FwaTo6VjFiBnByb3RvMw',
)

/**
 * @generated from message api.v1.HiRequest
 */
export type HiRequest = Message<'api.v1.HiRequest'> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string
}

/**
 * Describes the message api.v1.HiRequest.
 * Use `create(HiRequestSchema)` to create a new message.
 */
export const HiRequestSchema: GenMessage<HiRequest> /*@__PURE__*/ = messageDesc(file_api_v1_hi, 0)

/**
 * @generated from message api.v1.HiResponse
 */
export type HiResponse = Message<'api.v1.HiResponse'> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string
}

/**
 * Describes the message api.v1.HiResponse.
 * Use `create(HiResponseSchema)` to create a new message.
 */
export const HiResponseSchema: GenMessage<HiResponse> /*@__PURE__*/ = messageDesc(file_api_v1_hi, 1)

/**
 * @generated from message api.v1.WriteRequest
 */
export type WriteRequest = Message<'api.v1.WriteRequest'> & {
  /**
   * @generated from field: string data = 1;
   */
  data: string
}

/**
 * Describes the message api.v1.WriteRequest.
 * Use `create(WriteRequestSchema)` to create a new message.
 */
export const WriteRequestSchema: GenMessage<WriteRequest> /*@__PURE__*/ = messageDesc(
  file_api_v1_hi,
  2,
)

/**
 * @generated from message api.v1.WriteResponse
 */
export type WriteResponse = Message<'api.v1.WriteResponse'> & {
  /**
   * @generated from field: string data = 1;
   */
  data: string
}

/**
 * Describes the message api.v1.WriteResponse.
 * Use `create(WriteResponseSchema)` to create a new message.
 */
export const WriteResponseSchema: GenMessage<WriteResponse> /*@__PURE__*/ = messageDesc(
  file_api_v1_hi,
  3,
)

/**
 * @generated from message api.v1.ServerStreamRequest
 */
export type ServerStreamRequest = Message<'api.v1.ServerStreamRequest'> & {
  /**
   * @generated from field: string greeting = 1;
   */
  greeting: string
}

/**
 * Describes the message api.v1.ServerStreamRequest.
 * Use `create(ServerStreamRequestSchema)` to create a new message.
 */
export const ServerStreamRequestSchema: GenMessage<ServerStreamRequest> /*@__PURE__*/ = messageDesc(
  file_api_v1_hi,
  4,
)

/**
 * @generated from message api.v1.ServerStreamResponse
 */
export type ServerStreamResponse = Message<'api.v1.ServerStreamResponse'> & {
  /**
   * @generated from field: string reply = 1;
   */
  reply: string
}

/**
 * Describes the message api.v1.ServerStreamResponse.
 * Use `create(ServerStreamResponseSchema)` to create a new message.
 */
export const ServerStreamResponseSchema: GenMessage<ServerStreamResponse> /*@__PURE__*/ =
  messageDesc(file_api_v1_hi, 5)

/**
 * @generated from message api.v1.ClientStreamRequest
 */
export type ClientStreamRequest = Message<'api.v1.ClientStreamRequest'> & {
  /**
   * @generated from field: string greeting = 1;
   */
  greeting: string
}

/**
 * Describes the message api.v1.ClientStreamRequest.
 * Use `create(ClientStreamRequestSchema)` to create a new message.
 */
export const ClientStreamRequestSchema: GenMessage<ClientStreamRequest> /*@__PURE__*/ = messageDesc(
  file_api_v1_hi,
  6,
)

/**
 * @generated from message api.v1.ClientStreamResponse
 */
export type ClientStreamResponse = Message<'api.v1.ClientStreamResponse'> & {
  /**
   * @generated from field: string greeting = 1;
   */
  greeting: string
}

/**
 * Describes the message api.v1.ClientStreamResponse.
 * Use `create(ClientStreamResponseSchema)` to create a new message.
 */
export const ClientStreamResponseSchema: GenMessage<ClientStreamResponse> /*@__PURE__*/ =
  messageDesc(file_api_v1_hi, 7)

/**
 * @generated from message api.v1.BothStreamRequest
 */
export type BothStreamRequest = Message<'api.v1.BothStreamRequest'> & {
  /**
   * @generated from field: string greeting = 1;
   */
  greeting: string
}

/**
 * Describes the message api.v1.BothStreamRequest.
 * Use `create(BothStreamRequestSchema)` to create a new message.
 */
export const BothStreamRequestSchema: GenMessage<BothStreamRequest> /*@__PURE__*/ = messageDesc(
  file_api_v1_hi,
  8,
)

/**
 * @generated from message api.v1.BothStreamResponse
 */
export type BothStreamResponse = Message<'api.v1.BothStreamResponse'> & {
  /**
   * @generated from field: string greeting = 1;
   */
  greeting: string
}

/**
 * Describes the message api.v1.BothStreamResponse.
 * Use `create(BothStreamResponseSchema)` to create a new message.
 */
export const BothStreamResponseSchema: GenMessage<BothStreamResponse> /*@__PURE__*/ = messageDesc(
  file_api_v1_hi,
  9,
)

/**
 * @generated from service api.v1.HiService
 */
export const HiService: GenService<{
  /**
   * @generated from rpc api.v1.HiService.Hi
   */
  hi: {
    methodKind: 'unary'
    input: typeof HiRequestSchema
    output: typeof HiResponseSchema
  }
  /**
   * @generated from rpc api.v1.HiService.Write
   */
  write: {
    methodKind: 'unary'
    input: typeof WriteRequestSchema
    output: typeof WriteResponseSchema
  }
  /**
   * @generated from rpc api.v1.HiService.ServerStream
   */
  serverStream: {
    methodKind: 'server_streaming'
    input: typeof ServerStreamRequestSchema
    output: typeof ServerStreamResponseSchema
  }
  /**
   * @generated from rpc api.v1.HiService.ClientStream
   */
  clientStream: {
    methodKind: 'client_streaming'
    input: typeof ClientStreamRequestSchema
    output: typeof ClientStreamResponseSchema
  }
  /**
   * @generated from rpc api.v1.HiService.BothStream
   */
  bothStream: {
    methodKind: 'bidi_streaming'
    input: typeof BothStreamRequestSchema
    output: typeof BothStreamResponseSchema
  }
}> /*@__PURE__*/ = serviceDesc(file_api_v1_hi, 0)
