// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/scryinfo/dot/dot"
	"github.com/scryinfo/dot/line/certificate"
	"github.com/scryinfo/dot/line/etcddot"
	"github.com/scryinfo/dot/line/rpcdot"
	"github.com/scryinfo/dot/line/sconfig"
)

// Injectors from wire.go:

func InitializeService() (*Line, func(), error) {
	sConfig, err := sconfig.NewConfig()
	if err != nil {
		return nil, nil, err
	}
	lineConfig, err := NewLineConfig(sConfig)
	if err != nil {
		return nil, nil, err
	}
	logConfig := &lineConfig.Log
	v := dot.NewLogger(logConfig)
	grpcClientEtcdConfig := &lineConfig.GrpcClientEtcd
	baseCertificate := certificate.NewBaseCertificate(v)
	clientConfig := &lineConfig.EtcdClient
	client, cleanup, err := etcddot.NewClient(clientConfig, v)
	if err != nil {
		return nil, nil, err
	}
	grpcClientEtcd, err := rpcdot.NewGrpcClientEtcd(grpcClientEtcdConfig, sConfig, baseCertificate, client, v)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	hiServiceClient := NewHiServiceClient(grpcClientEtcd)
	line := &Line{
		SConfig:         sConfig,
		Logger:          v,
		HiServiceClient: hiServiceClient,
	}
	return line, func() {
		cleanup()
	}, nil
}
