// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: config.proto

package rpc

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//findDot
type FindReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dirs []string `protobuf:"bytes,1,rep,name=dirs,proto3" json:"dirs,omitempty"` //目录集合
}

func (x *FindReq) Reset() {
	*x = FindReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindReq) ProtoMessage() {}

func (x *FindReq) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindReq.ProtoReflect.Descriptor instead.
func (*FindReq) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0}
}

func (x *FindReq) GetDirs() []string {
	if x != nil {
		return x.Dirs
	}
	return nil
}

type FindRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DotsInfo    string   `protobuf:"bytes,1,opt,name=dotsInfo,proto3" json:"dotsInfo,omitempty"`       //组件信息（json）
	NoExistDirs []string `protobuf:"bytes,2,rep,name=noExistDirs,proto3" json:"noExistDirs,omitempty"` //不存在的目录集合
	Error       string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`             //错误信息
}

func (x *FindRes) Reset() {
	*x = FindRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRes) ProtoMessage() {}

func (x *FindRes) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRes.ProtoReflect.Descriptor instead.
func (*FindRes) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{1}
}

func (x *FindRes) GetDotsInfo() string {
	if x != nil {
		return x.DotsInfo
	}
	return ""
}

func (x *FindRes) GetNoExistDirs() []string {
	if x != nil {
		return x.NoExistDirs
	}
	return nil
}

func (x *FindRes) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

//importfile
type ImportReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filepath string `protobuf:"bytes,1,opt,name=filepath,proto3" json:"filepath,omitempty"` //导入文件的路径
}

func (x *ImportReq) Reset() {
	*x = ImportReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImportReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportReq) ProtoMessage() {}

func (x *ImportReq) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportReq.ProtoReflect.Descriptor instead.
func (*ImportReq) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{2}
}

func (x *ImportReq) GetFilepath() string {
	if x != nil {
		return x.Filepath
	}
	return ""
}

type ImportRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Json  string `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`   //返回导入文件的内容
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` //导入出错
}

func (x *ImportRes) Reset() {
	*x = ImportRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImportRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportRes) ProtoMessage() {}

func (x *ImportRes) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportRes.ProtoReflect.Descriptor instead.
func (*ImportRes) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{3}
}

func (x *ImportRes) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

func (x *ImportRes) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

//exportfile
type ExportReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Configdata string   `protobuf:"bytes,1,opt,name=configdata,proto3" json:"configdata,omitempty"` //配置数据信息
	Filename   []string `protobuf:"bytes,2,rep,name=filename,proto3" json:"filename,omitempty"`     //导出的文件名
	Dotdata    string   `protobuf:"bytes,3,opt,name=dotdata,proto3" json:"dotdata,omitempty"`       //组件数据信息
}

func (x *ExportReq) Reset() {
	*x = ExportReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExportReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportReq) ProtoMessage() {}

func (x *ExportReq) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportReq.ProtoReflect.Descriptor instead.
func (*ExportReq) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{4}
}

func (x *ExportReq) GetConfigdata() string {
	if x != nil {
		return x.Configdata
	}
	return ""
}

func (x *ExportReq) GetFilename() []string {
	if x != nil {
		return x.Filename
	}
	return nil
}

func (x *ExportReq) GetDotdata() string {
	if x != nil {
		return x.Dotdata
	}
	return ""
}

type ExportRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"` //导出是否成功
}

func (x *ExportRes) Reset() {
	*x = ExportRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExportRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportRes) ProtoMessage() {}

func (x *ExportRes) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportRes.ProtoReflect.Descriptor instead.
func (*ExportRes) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{5}
}

func (x *ExportRes) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_config_proto protoreflect.FileDescriptor

var file_config_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03,
	0x72, 0x70, 0x63, 0x22, 0x1d, 0x0a, 0x07, 0x46, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x69, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x64, 0x69,
	0x72, 0x73, 0x22, 0x5d, 0x0a, 0x07, 0x46, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x12, 0x1a, 0x0a,
	0x08, 0x64, 0x6f, 0x74, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x64, 0x6f, 0x74, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x20, 0x0a, 0x0b, 0x6e, 0x6f, 0x45,
	0x78, 0x69, 0x73, 0x74, 0x44, 0x69, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b,
	0x6e, 0x6f, 0x45, 0x78, 0x69, 0x73, 0x74, 0x44, 0x69, 0x72, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x22, 0x27, 0x0a, 0x09, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1a,
	0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x70, 0x61, 0x74, 0x68, 0x22, 0x35, 0x0a, 0x09, 0x49, 0x6d,
	0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6a, 0x73, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6a, 0x73, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x22, 0x61, 0x0a, 0x09, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1e,
	0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1a,
	0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x6f,
	0x74, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x6f, 0x74,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x21, 0x0a, 0x09, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x32, 0xa2, 0x02, 0x0a, 0x0d, 0x44, 0x6f, 0x74, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x46, 0x61, 0x63, 0x65, 0x12, 0x25, 0x0a, 0x07, 0x46, 0x69, 0x6e,
	0x64, 0x44, 0x6f, 0x74, 0x12, 0x0c, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x52,
	0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x73,
	0x12, 0x30, 0x0a, 0x0e, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x42, 0x79, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x12, 0x0e, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x52,
	0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x52,
	0x65, 0x73, 0x12, 0x2d, 0x0a, 0x0b, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x42, 0x79, 0x44, 0x6f,
	0x74, 0x12, 0x0e, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65,
	0x71, 0x1a, 0x0e, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65,
	0x73, 0x12, 0x2c, 0x0a, 0x0a, 0x49, 0x6e, 0x69, 0x74, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x12,
	0x0e, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x1a,
	0x0e, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x12,
	0x2e, 0x0a, 0x0c, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12,
	0x0e, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x1a,
	0x0e, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x12,
	0x2b, 0x0a, 0x09, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x44, 0x6f, 0x74, 0x12, 0x0e, 0x2e, 0x72,
	0x70, 0x63, 0x2e, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x72,
	0x70, 0x63, 0x2e, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x42, 0x02, 0x48, 0x03,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_config_proto_rawDescOnce sync.Once
	file_config_proto_rawDescData = file_config_proto_rawDesc
)

func file_config_proto_rawDescGZIP() []byte {
	file_config_proto_rawDescOnce.Do(func() {
		file_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_config_proto_rawDescData)
	})
	return file_config_proto_rawDescData
}

var file_config_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_config_proto_goTypes = []interface{}{
	(*FindReq)(nil),   // 0: rpc.FindReq
	(*FindRes)(nil),   // 1: rpc.FindRes
	(*ImportReq)(nil), // 2: rpc.ImportReq
	(*ImportRes)(nil), // 3: rpc.ImportRes
	(*ExportReq)(nil), // 4: rpc.ExportReq
	(*ExportRes)(nil), // 5: rpc.ExportRes
}
var file_config_proto_depIdxs = []int32{
	0, // 0: rpc.DotConfigFace.FindDot:input_type -> rpc.FindReq
	2, // 1: rpc.DotConfigFace.ImportByConfig:input_type -> rpc.ImportReq
	2, // 2: rpc.DotConfigFace.ImportByDot:input_type -> rpc.ImportReq
	2, // 3: rpc.DotConfigFace.InitImport:input_type -> rpc.ImportReq
	4, // 4: rpc.DotConfigFace.ExportConfig:input_type -> rpc.ExportReq
	4, // 5: rpc.DotConfigFace.ExportDot:input_type -> rpc.ExportReq
	1, // 6: rpc.DotConfigFace.FindDot:output_type -> rpc.FindRes
	3, // 7: rpc.DotConfigFace.ImportByConfig:output_type -> rpc.ImportRes
	3, // 8: rpc.DotConfigFace.ImportByDot:output_type -> rpc.ImportRes
	3, // 9: rpc.DotConfigFace.InitImport:output_type -> rpc.ImportRes
	5, // 10: rpc.DotConfigFace.ExportConfig:output_type -> rpc.ExportRes
	5, // 11: rpc.DotConfigFace.ExportDot:output_type -> rpc.ExportRes
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_config_proto_init() }
func file_config_proto_init() {
	if File_config_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_config_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImportReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImportRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExportReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExportRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_config_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_config_proto_goTypes,
		DependencyIndexes: file_config_proto_depIdxs,
		MessageInfos:      file_config_proto_msgTypes,
	}.Build()
	File_config_proto = out.File
	file_config_proto_rawDesc = nil
	file_config_proto_goTypes = nil
	file_config_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DotConfigFaceClient is the client API for DotConfigFace service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DotConfigFaceClient interface {
	FindDot(ctx context.Context, in *FindReq, opts ...grpc.CallOption) (*FindRes, error)
	//文件导入
	ImportByConfig(ctx context.Context, in *ImportReq, opts ...grpc.CallOption) (*ImportRes, error)
	ImportByDot(ctx context.Context, in *ImportReq, opts ...grpc.CallOption) (*ImportRes, error)
	InitImport(ctx context.Context, in *ImportReq, opts ...grpc.CallOption) (*ImportRes, error)
	//导出文件
	ExportConfig(ctx context.Context, in *ExportReq, opts ...grpc.CallOption) (*ExportRes, error)
	ExportDot(ctx context.Context, in *ExportReq, opts ...grpc.CallOption) (*ExportRes, error)
}

type dotConfigFaceClient struct {
	cc grpc.ClientConnInterface
}

func NewDotConfigFaceClient(cc grpc.ClientConnInterface) DotConfigFaceClient {
	return &dotConfigFaceClient{cc}
}

func (c *dotConfigFaceClient) FindDot(ctx context.Context, in *FindReq, opts ...grpc.CallOption) (*FindRes, error) {
	out := new(FindRes)
	err := c.cc.Invoke(ctx, "/rpc.DotConfigFace/FindDot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dotConfigFaceClient) ImportByConfig(ctx context.Context, in *ImportReq, opts ...grpc.CallOption) (*ImportRes, error) {
	out := new(ImportRes)
	err := c.cc.Invoke(ctx, "/rpc.DotConfigFace/ImportByConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dotConfigFaceClient) ImportByDot(ctx context.Context, in *ImportReq, opts ...grpc.CallOption) (*ImportRes, error) {
	out := new(ImportRes)
	err := c.cc.Invoke(ctx, "/rpc.DotConfigFace/ImportByDot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dotConfigFaceClient) InitImport(ctx context.Context, in *ImportReq, opts ...grpc.CallOption) (*ImportRes, error) {
	out := new(ImportRes)
	err := c.cc.Invoke(ctx, "/rpc.DotConfigFace/InitImport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dotConfigFaceClient) ExportConfig(ctx context.Context, in *ExportReq, opts ...grpc.CallOption) (*ExportRes, error) {
	out := new(ExportRes)
	err := c.cc.Invoke(ctx, "/rpc.DotConfigFace/ExportConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dotConfigFaceClient) ExportDot(ctx context.Context, in *ExportReq, opts ...grpc.CallOption) (*ExportRes, error) {
	out := new(ExportRes)
	err := c.cc.Invoke(ctx, "/rpc.DotConfigFace/ExportDot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DotConfigFaceServer is the server API for DotConfigFace service.
type DotConfigFaceServer interface {
	FindDot(context.Context, *FindReq) (*FindRes, error)
	//文件导入
	ImportByConfig(context.Context, *ImportReq) (*ImportRes, error)
	ImportByDot(context.Context, *ImportReq) (*ImportRes, error)
	InitImport(context.Context, *ImportReq) (*ImportRes, error)
	//导出文件
	ExportConfig(context.Context, *ExportReq) (*ExportRes, error)
	ExportDot(context.Context, *ExportReq) (*ExportRes, error)
}

// UnimplementedDotConfigFaceServer can be embedded to have forward compatible implementations.
type UnimplementedDotConfigFaceServer struct {
}

func (*UnimplementedDotConfigFaceServer) FindDot(context.Context, *FindReq) (*FindRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindDot not implemented")
}
func (*UnimplementedDotConfigFaceServer) ImportByConfig(context.Context, *ImportReq) (*ImportRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportByConfig not implemented")
}
func (*UnimplementedDotConfigFaceServer) ImportByDot(context.Context, *ImportReq) (*ImportRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportByDot not implemented")
}
func (*UnimplementedDotConfigFaceServer) InitImport(context.Context, *ImportReq) (*ImportRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitImport not implemented")
}
func (*UnimplementedDotConfigFaceServer) ExportConfig(context.Context, *ExportReq) (*ExportRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExportConfig not implemented")
}
func (*UnimplementedDotConfigFaceServer) ExportDot(context.Context, *ExportReq) (*ExportRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExportDot not implemented")
}

func RegisterDotConfigFaceServer(s *grpc.Server, srv DotConfigFaceServer) {
	s.RegisterService(&_DotConfigFace_serviceDesc, srv)
}

func _DotConfigFace_FindDot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DotConfigFaceServer).FindDot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.DotConfigFace/FindDot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DotConfigFaceServer).FindDot(ctx, req.(*FindReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DotConfigFace_ImportByConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DotConfigFaceServer).ImportByConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.DotConfigFace/ImportByConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DotConfigFaceServer).ImportByConfig(ctx, req.(*ImportReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DotConfigFace_ImportByDot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DotConfigFaceServer).ImportByDot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.DotConfigFace/ImportByDot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DotConfigFaceServer).ImportByDot(ctx, req.(*ImportReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DotConfigFace_InitImport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DotConfigFaceServer).InitImport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.DotConfigFace/InitImport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DotConfigFaceServer).InitImport(ctx, req.(*ImportReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DotConfigFace_ExportConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DotConfigFaceServer).ExportConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.DotConfigFace/ExportConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DotConfigFaceServer).ExportConfig(ctx, req.(*ExportReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DotConfigFace_ExportDot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DotConfigFaceServer).ExportDot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.DotConfigFace/ExportDot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DotConfigFaceServer).ExportDot(ctx, req.(*ExportReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _DotConfigFace_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.DotConfigFace",
	HandlerType: (*DotConfigFaceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindDot",
			Handler:    _DotConfigFace_FindDot_Handler,
		},
		{
			MethodName: "ImportByConfig",
			Handler:    _DotConfigFace_ImportByConfig_Handler,
		},
		{
			MethodName: "ImportByDot",
			Handler:    _DotConfigFace_ImportByDot_Handler,
		},
		{
			MethodName: "InitImport",
			Handler:    _DotConfigFace_InitImport_Handler,
		},
		{
			MethodName: "ExportConfig",
			Handler:    _DotConfigFace_ExportConfig_Handler,
		},
		{
			MethodName: "ExportDot",
			Handler:    _DotConfigFace_ExportDot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "config.proto",
}
