// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: api/v1/hi.proto

package apiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HiService_Hi_FullMethodName           = "/api.v1.HiService/Hi"
	HiService_Write_FullMethodName        = "/api.v1.HiService/Write"
	HiService_ServerStream_FullMethodName = "/api.v1.HiService/ServerStream"
	HiService_ClientStream_FullMethodName = "/api.v1.HiService/ClientStream"
	HiService_BothStream_FullMethodName   = "/api.v1.HiService/BothStream"
)

// HiServiceClient is the client API for HiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HiServiceClient interface {
	Hi(ctx context.Context, in *HiRequest, opts ...grpc.CallOption) (*HiResponse, error)
	Write(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error)
	ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ServerStreamResponse], error)
	ClientStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ClientStreamRequest, ClientStreamResponse], error)
	BothStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BothStreamRequest, BothStreamResponse], error)
}

type hiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHiServiceClient(cc grpc.ClientConnInterface) HiServiceClient {
	return &hiServiceClient{cc}
}

func (c *hiServiceClient) Hi(ctx context.Context, in *HiRequest, opts ...grpc.CallOption) (*HiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HiResponse)
	err := c.cc.Invoke(ctx, HiService_Hi_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hiServiceClient) Write(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteResponse)
	err := c.cc.Invoke(ctx, HiService_Write_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hiServiceClient) ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ServerStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HiService_ServiceDesc.Streams[0], HiService_ServerStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ServerStreamRequest, ServerStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HiService_ServerStreamClient = grpc.ServerStreamingClient[ServerStreamResponse]

func (c *hiServiceClient) ClientStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ClientStreamRequest, ClientStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HiService_ServiceDesc.Streams[1], HiService_ClientStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientStreamRequest, ClientStreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HiService_ClientStreamClient = grpc.ClientStreamingClient[ClientStreamRequest, ClientStreamResponse]

func (c *hiServiceClient) BothStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BothStreamRequest, BothStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HiService_ServiceDesc.Streams[2], HiService_BothStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BothStreamRequest, BothStreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HiService_BothStreamClient = grpc.BidiStreamingClient[BothStreamRequest, BothStreamResponse]

// HiServiceServer is the server API for HiService service.
// All implementations must embed UnimplementedHiServiceServer
// for forward compatibility.
type HiServiceServer interface {
	Hi(context.Context, *HiRequest) (*HiResponse, error)
	Write(context.Context, *WriteRequest) (*WriteResponse, error)
	ServerStream(*ServerStreamRequest, grpc.ServerStreamingServer[ServerStreamResponse]) error
	ClientStream(grpc.ClientStreamingServer[ClientStreamRequest, ClientStreamResponse]) error
	BothStream(grpc.BidiStreamingServer[BothStreamRequest, BothStreamResponse]) error
	mustEmbedUnimplementedHiServiceServer()
}

// UnimplementedHiServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHiServiceServer struct{}

func (UnimplementedHiServiceServer) Hi(context.Context, *HiRequest) (*HiResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Hi not implemented")
}
func (UnimplementedHiServiceServer) Write(context.Context, *WriteRequest) (*WriteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Write not implemented")
}
func (UnimplementedHiServiceServer) ServerStream(*ServerStreamRequest, grpc.ServerStreamingServer[ServerStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method ServerStream not implemented")
}
func (UnimplementedHiServiceServer) ClientStream(grpc.ClientStreamingServer[ClientStreamRequest, ClientStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method ClientStream not implemented")
}
func (UnimplementedHiServiceServer) BothStream(grpc.BidiStreamingServer[BothStreamRequest, BothStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method BothStream not implemented")
}
func (UnimplementedHiServiceServer) mustEmbedUnimplementedHiServiceServer() {}
func (UnimplementedHiServiceServer) testEmbeddedByValue()                   {}

// UnsafeHiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HiServiceServer will
// result in compilation errors.
type UnsafeHiServiceServer interface {
	mustEmbedUnimplementedHiServiceServer()
}

func RegisterHiServiceServer(s grpc.ServiceRegistrar, srv HiServiceServer) {
	// If the following call panics, it indicates UnimplementedHiServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HiService_ServiceDesc, srv)
}

func _HiService_Hi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HiServiceServer).Hi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HiService_Hi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HiServiceServer).Hi(ctx, req.(*HiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HiService_Write_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HiServiceServer).Write(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HiService_Write_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HiServiceServer).Write(ctx, req.(*WriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HiService_ServerStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ServerStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HiServiceServer).ServerStream(m, &grpc.GenericServerStream[ServerStreamRequest, ServerStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HiService_ServerStreamServer = grpc.ServerStreamingServer[ServerStreamResponse]

func _HiService_ClientStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HiServiceServer).ClientStream(&grpc.GenericServerStream[ClientStreamRequest, ClientStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HiService_ClientStreamServer = grpc.ClientStreamingServer[ClientStreamRequest, ClientStreamResponse]

func _HiService_BothStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HiServiceServer).BothStream(&grpc.GenericServerStream[BothStreamRequest, BothStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HiService_BothStreamServer = grpc.BidiStreamingServer[BothStreamRequest, BothStreamResponse]

// HiService_ServiceDesc is the grpc.ServiceDesc for HiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.HiService",
	HandlerType: (*HiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hi",
			Handler:    _HiService_Hi_Handler,
		},
		{
			MethodName: "Write",
			Handler:    _HiService_Write_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ServerStream",
			Handler:       _HiService_ServerStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ClientStream",
			Handler:       _HiService_ClientStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "BothStream",
			Handler:       _HiService_BothStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/v1/hi.proto",
}
